// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Introduction  string                 `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateUserBasicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Introduction  string                 `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserBasicInfoRequest) Reset() {
	*x = UpdateUserBasicInfoRequest{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserBasicInfoRequest) ProtoMessage() {}

func (x *UpdateUserBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserBasicInfoRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserBasicInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserBasicInfoRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserBasicInfoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserBasicInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserBasicInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserBasicInfoRequest) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type UpdateUserBasicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserBasicInfoResponse) Reset() {
	*x = UpdateUserBasicInfoResponse{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserBasicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserBasicInfoResponse) ProtoMessage() {}

func (x *UpdateUserBasicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserBasicInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserBasicInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserBasicInfoResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserBasicInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserBasicInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserBasicInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Introduction  string                 `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserResponse) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *GetUserResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateOrUpdateMiniProgramAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                // 微信 AppID
	OpenId        string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`             // OpenID
	UnionId       string                 `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`          // UnionID (可选)
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`                       // 昵称
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                           // 头像
	SessionKey    string                 `protobuf:"bytes,6,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"` // SessionKey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateMiniProgramAccountRequest) Reset() {
	*x = CreateOrUpdateMiniProgramAccountRequest{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateMiniProgramAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMiniProgramAccountRequest) ProtoMessage() {}

func (x *CreateOrUpdateMiniProgramAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMiniProgramAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMiniProgramAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateOrUpdateMiniProgramAccountRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type CreateOrUpdateOfficialAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`       // 微信 AppID
	OpenId        string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`    // OpenID
	UnionId       string                 `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"` // UnionID (可选)
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`              // 昵称
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                  // 头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateOfficialAccountRequest) Reset() {
	*x = CreateOrUpdateOfficialAccountRequest{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateOfficialAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateOfficialAccountRequest) ProtoMessage() {}

func (x *CreateOrUpdateOfficialAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateOfficialAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateOfficialAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrUpdateOfficialAccountRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateOrUpdateOfficialAccountRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *CreateOrUpdateOfficialAccountRequest) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *CreateOrUpdateOfficialAccountRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateOrUpdateOfficialAccountRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetWechatAccountByOpenIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`    // 微信 AppID
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`           // 平台: mini/oa
	OpenId        string                 `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // OpenID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWechatAccountByOpenIDRequest) Reset() {
	*x = GetWechatAccountByOpenIDRequest{}
	mi := &file_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWechatAccountByOpenIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatAccountByOpenIDRequest) ProtoMessage() {}

func (x *GetWechatAccountByOpenIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatAccountByOpenIDRequest.ProtoReflect.Descriptor instead.
func (*GetWechatAccountByOpenIDRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetWechatAccountByOpenIDRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetWechatAccountByOpenIDRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetWechatAccountByOpenIDRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type WechatAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`            // 账号ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 关联的用户ID
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                         // 微信 AppID
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                                // 平台
	OpenId        string                 `protobuf:"bytes,5,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`                      // OpenID
	UnionId       string                 `protobuf:"bytes,6,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`                   // UnionID
	Nickname      string                 `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`                                // 昵称
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`                                    // 头像
	IsNewAccount  bool                   `protobuf:"varint,9,opt,name=is_new_account,json=isNewAccount,proto3" json:"is_new_account,omitempty"` // 是否新账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatAccountResponse) Reset() {
	*x = WechatAccountResponse{}
	mi := &file_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatAccountResponse) ProtoMessage() {}

func (x *WechatAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatAccountResponse.ProtoReflect.Descriptor instead.
func (*WechatAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *WechatAccountResponse) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WechatAccountResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WechatAccountResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WechatAccountResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WechatAccountResponse) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *WechatAccountResponse) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *WechatAccountResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *WechatAccountResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *WechatAccountResponse) GetIsNewAccount() bool {
	if x != nil {
		return x.IsNewAccount
	}
	return false
}

type CreateTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           uint32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`          // 0-未知, 1-男, 2-女
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"` // 生日
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTesteeRequest) Reset() {
	*x = CreateTesteeRequest{}
	mi := &file_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTesteeRequest) ProtoMessage() {}

func (x *CreateTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTesteeRequest.ProtoReflect.Descriptor instead.
func (*CreateTesteeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTesteeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTesteeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTesteeRequest) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CreateTesteeRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

type UpdateTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           uint32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTesteeRequest) Reset() {
	*x = UpdateTesteeRequest{}
	mi := &file_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTesteeRequest) ProtoMessage() {}

func (x *UpdateTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTesteeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTesteeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTesteeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateTesteeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTesteeRequest) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UpdateTesteeRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

type GetTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTesteeRequest) Reset() {
	*x = GetTesteeRequest{}
	mi := &file_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTesteeRequest) ProtoMessage() {}

func (x *GetTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTesteeRequest.ProtoReflect.Descriptor instead.
func (*GetTesteeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetTesteeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TesteeExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeExistsRequest) Reset() {
	*x = TesteeExistsRequest{}
	mi := &file_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeExistsRequest) ProtoMessage() {}

func (x *TesteeExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeExistsRequest.ProtoReflect.Descriptor instead.
func (*TesteeExistsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *TesteeExistsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TesteeExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeExistsResponse) Reset() {
	*x = TesteeExistsResponse{}
	mi := &file_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeExistsResponse) ProtoMessage() {}

func (x *TesteeExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeExistsResponse.ProtoReflect.Descriptor instead.
func (*TesteeExistsResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *TesteeExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type TesteeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           uint32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"` // 计算出的年龄
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeResponse) Reset() {
	*x = TesteeResponse{}
	mi := &file_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeResponse) ProtoMessage() {}

func (x *TesteeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeResponse.ProtoReflect.Descriptor instead.
func (*TesteeResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *TesteeResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TesteeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TesteeResponse) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *TesteeResponse) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *TesteeResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type CreateWriterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWriterRequest) Reset() {
	*x = CreateWriterRequest{}
	mi := &file_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWriterRequest) ProtoMessage() {}

func (x *CreateWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWriterRequest.ProtoReflect.Descriptor instead.
func (*CreateWriterRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *CreateWriterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateWriterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWriterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWriterRequest) Reset() {
	*x = UpdateWriterRequest{}
	mi := &file_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWriterRequest) ProtoMessage() {}

func (x *UpdateWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWriterRequest.ProtoReflect.Descriptor instead.
func (*UpdateWriterRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateWriterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWriterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWriterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWriterRequest) Reset() {
	*x = GetWriterRequest{}
	mi := &file_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWriterRequest) ProtoMessage() {}

func (x *GetWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWriterRequest.ProtoReflect.Descriptor instead.
func (*GetWriterRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetWriterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type WriterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriterResponse) Reset() {
	*x = WriterResponse{}
	mi := &file_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriterResponse) ProtoMessage() {}

func (x *WriterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriterResponse.ProtoReflect.Descriptor instead.
func (*WriterResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *WriterResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WriterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\"\n" +
	"\fintroduction\x18\x06 \x01(\tR\fintroduction\"\x91\x01\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\"\xd5\x01\n" +
	"\x1aUpdateUserBasicInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\"\n" +
	"\fintroduction\x18\a \x01(\tR\fintroduction\"\x86\x01\n" +
	"\x1bUpdateUserBasicInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xe2\x01\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\"\n" +
	"\fintroduction\x18\a \x01(\tR\fintroduction\x12\x16\n" +
	"\x06status\x18\b \x01(\rR\x06status\"\xc9\x01\n" +
	"'CreateOrUpdateMiniProgramAccountRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vsession_key\x18\x06 \x01(\tR\n" +
	"sessionKey\"\xa5\x01\n" +
	"$CreateOrUpdateOfficialAccountRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"m\n" +
	"\x1fGetWechatAccountByOpenIDRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x17\n" +
	"\aopen_id\x18\x03 \x01(\tR\x06openId\"\x90\x02\n" +
	"\x15WechatAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x17\n" +
	"\aopen_id\x18\x05 \x01(\tR\x06openId\x12\x19\n" +
	"\bunion_id\x18\x06 \x01(\tR\aunionId\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12$\n" +
	"\x0eis_new_account\x18\t \x01(\bR\fisNewAccount\"\x8c\x01\n" +
	"\x13CreateTesteeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\rR\x03sex\x126\n" +
	"\bbirthday\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\"\x8c\x01\n" +
	"\x13UpdateTesteeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\rR\x03sex\x126\n" +
	"\bbirthday\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\"+\n" +
	"\x10GetTesteeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x13TesteeExistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x14TesteeExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x99\x01\n" +
	"\x0eTesteeResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\rR\x03sex\x126\n" +
	"\bbirthday\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\"B\n" +
	"\x13CreateWriterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x13UpdateWriterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x10GetWriterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"=\n" +
	"\x0eWriterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xdd\a\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12Z\n" +
	"\x13UpdateUserBasicInfo\x12 .user.UpdateUserBasicInfoRequest\x1a!.user.UpdateUserBasicInfoResponse\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12n\n" +
	" CreateOrUpdateMiniProgramAccount\x12-.user.CreateOrUpdateMiniProgramAccountRequest\x1a\x1b.user.WechatAccountResponse\x12h\n" +
	"\x1dCreateOrUpdateOfficialAccount\x12*.user.CreateOrUpdateOfficialAccountRequest\x1a\x1b.user.WechatAccountResponse\x12^\n" +
	"\x18GetWechatAccountByOpenID\x12%.user.GetWechatAccountByOpenIDRequest\x1a\x1b.user.WechatAccountResponse\x12?\n" +
	"\fCreateTestee\x12\x19.user.CreateTesteeRequest\x1a\x14.user.TesteeResponse\x12?\n" +
	"\fUpdateTestee\x12\x19.user.UpdateTesteeRequest\x1a\x14.user.TesteeResponse\x129\n" +
	"\tGetTestee\x12\x16.user.GetTesteeRequest\x1a\x14.user.TesteeResponse\x12E\n" +
	"\fTesteeExists\x12\x19.user.TesteeExistsRequest\x1a\x1a.user.TesteeExistsResponse\x12?\n" +
	"\fCreateWriter\x12\x19.user.CreateWriterRequest\x1a\x14.user.WriterResponse\x12?\n" +
	"\fUpdateWriter\x12\x19.user.UpdateWriterRequest\x1a\x14.user.WriterResponse\x129\n" +
	"\tGetWriter\x12\x16.user.GetWriterRequest\x1a\x14.user.WriterResponseBQZOgithub.com/fangcun-mount/qs-server/internal/apiserver/interface/grpc/proto/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),                       // 0: user.CreateUserRequest
	(*CreateUserResponse)(nil),                      // 1: user.CreateUserResponse
	(*UpdateUserBasicInfoRequest)(nil),              // 2: user.UpdateUserBasicInfoRequest
	(*UpdateUserBasicInfoResponse)(nil),             // 3: user.UpdateUserBasicInfoResponse
	(*GetUserRequest)(nil),                          // 4: user.GetUserRequest
	(*GetUserResponse)(nil),                         // 5: user.GetUserResponse
	(*CreateOrUpdateMiniProgramAccountRequest)(nil), // 6: user.CreateOrUpdateMiniProgramAccountRequest
	(*CreateOrUpdateOfficialAccountRequest)(nil),    // 7: user.CreateOrUpdateOfficialAccountRequest
	(*GetWechatAccountByOpenIDRequest)(nil),         // 8: user.GetWechatAccountByOpenIDRequest
	(*WechatAccountResponse)(nil),                   // 9: user.WechatAccountResponse
	(*CreateTesteeRequest)(nil),                     // 10: user.CreateTesteeRequest
	(*UpdateTesteeRequest)(nil),                     // 11: user.UpdateTesteeRequest
	(*GetTesteeRequest)(nil),                        // 12: user.GetTesteeRequest
	(*TesteeExistsRequest)(nil),                     // 13: user.TesteeExistsRequest
	(*TesteeExistsResponse)(nil),                    // 14: user.TesteeExistsResponse
	(*TesteeResponse)(nil),                          // 15: user.TesteeResponse
	(*CreateWriterRequest)(nil),                     // 16: user.CreateWriterRequest
	(*UpdateWriterRequest)(nil),                     // 17: user.UpdateWriterRequest
	(*GetWriterRequest)(nil),                        // 18: user.GetWriterRequest
	(*WriterResponse)(nil),                          // 19: user.WriterResponse
	(*timestamppb.Timestamp)(nil),                   // 20: google.protobuf.Timestamp
}
var file_user_user_proto_depIdxs = []int32{
	20, // 0: user.CreateTesteeRequest.birthday:type_name -> google.protobuf.Timestamp
	20, // 1: user.UpdateTesteeRequest.birthday:type_name -> google.protobuf.Timestamp
	20, // 2: user.TesteeResponse.birthday:type_name -> google.protobuf.Timestamp
	0,  // 3: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 4: user.UserService.UpdateUserBasicInfo:input_type -> user.UpdateUserBasicInfoRequest
	4,  // 5: user.UserService.GetUser:input_type -> user.GetUserRequest
	6,  // 6: user.UserService.CreateOrUpdateMiniProgramAccount:input_type -> user.CreateOrUpdateMiniProgramAccountRequest
	7,  // 7: user.UserService.CreateOrUpdateOfficialAccount:input_type -> user.CreateOrUpdateOfficialAccountRequest
	8,  // 8: user.UserService.GetWechatAccountByOpenID:input_type -> user.GetWechatAccountByOpenIDRequest
	10, // 9: user.UserService.CreateTestee:input_type -> user.CreateTesteeRequest
	11, // 10: user.UserService.UpdateTestee:input_type -> user.UpdateTesteeRequest
	12, // 11: user.UserService.GetTestee:input_type -> user.GetTesteeRequest
	13, // 12: user.UserService.TesteeExists:input_type -> user.TesteeExistsRequest
	16, // 13: user.UserService.CreateWriter:input_type -> user.CreateWriterRequest
	17, // 14: user.UserService.UpdateWriter:input_type -> user.UpdateWriterRequest
	18, // 15: user.UserService.GetWriter:input_type -> user.GetWriterRequest
	1,  // 16: user.UserService.CreateUser:output_type -> user.CreateUserResponse
	3,  // 17: user.UserService.UpdateUserBasicInfo:output_type -> user.UpdateUserBasicInfoResponse
	5,  // 18: user.UserService.GetUser:output_type -> user.GetUserResponse
	9,  // 19: user.UserService.CreateOrUpdateMiniProgramAccount:output_type -> user.WechatAccountResponse
	9,  // 20: user.UserService.CreateOrUpdateOfficialAccount:output_type -> user.WechatAccountResponse
	9,  // 21: user.UserService.GetWechatAccountByOpenID:output_type -> user.WechatAccountResponse
	15, // 22: user.UserService.CreateTestee:output_type -> user.TesteeResponse
	15, // 23: user.UserService.UpdateTestee:output_type -> user.TesteeResponse
	15, // 24: user.UserService.GetTestee:output_type -> user.TesteeResponse
	14, // 25: user.UserService.TesteeExists:output_type -> user.TesteeExistsResponse
	19, // 26: user.UserService.CreateWriter:output_type -> user.WriterResponse
	19, // 27: user.UserService.UpdateWriter:output_type -> user.WriterResponse
	19, // 28: user.UserService.GetWriter:output_type -> user.WriterResponse
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
