// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/apiserver/interface/grpc/proto/scale/scale.proto

package scale

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScaleService_GetScale_FullMethodName           = "/scale.ScaleService/GetScale"
	ScaleService_ListScales_FullMethodName         = "/scale.ScaleService/ListScales"
	ScaleService_GetScaleCategories_FullMethodName = "/scale.ScaleService/GetScaleCategories"
)

// ScaleServiceClient is the client API for ScaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 量表服务 - 对外提供查询功能
type ScaleServiceClient interface {
	// 获取量表详情
	GetScale(ctx context.Context, in *GetScaleRequest, opts ...grpc.CallOption) (*GetScaleResponse, error)
	// 获取量表列表（返回摘要信息，不含 factors）
	ListScales(ctx context.Context, in *ListScalesRequest, opts ...grpc.CallOption) (*ListScalesResponse, error)
	// 获取量表分类列表
	GetScaleCategories(ctx context.Context, in *GetScaleCategoriesRequest, opts ...grpc.CallOption) (*GetScaleCategoriesResponse, error)
}

type scaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScaleServiceClient(cc grpc.ClientConnInterface) ScaleServiceClient {
	return &scaleServiceClient{cc}
}

func (c *scaleServiceClient) GetScale(ctx context.Context, in *GetScaleRequest, opts ...grpc.CallOption) (*GetScaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScaleResponse)
	err := c.cc.Invoke(ctx, ScaleService_GetScale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scaleServiceClient) ListScales(ctx context.Context, in *ListScalesRequest, opts ...grpc.CallOption) (*ListScalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScalesResponse)
	err := c.cc.Invoke(ctx, ScaleService_ListScales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scaleServiceClient) GetScaleCategories(ctx context.Context, in *GetScaleCategoriesRequest, opts ...grpc.CallOption) (*GetScaleCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScaleCategoriesResponse)
	err := c.cc.Invoke(ctx, ScaleService_GetScaleCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScaleServiceServer is the server API for ScaleService service.
// All implementations must embed UnimplementedScaleServiceServer
// for forward compatibility.
//
// 量表服务 - 对外提供查询功能
type ScaleServiceServer interface {
	// 获取量表详情
	GetScale(context.Context, *GetScaleRequest) (*GetScaleResponse, error)
	// 获取量表列表（返回摘要信息，不含 factors）
	ListScales(context.Context, *ListScalesRequest) (*ListScalesResponse, error)
	// 获取量表分类列表
	GetScaleCategories(context.Context, *GetScaleCategoriesRequest) (*GetScaleCategoriesResponse, error)
	mustEmbedUnimplementedScaleServiceServer()
}

// UnimplementedScaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScaleServiceServer struct{}

func (UnimplementedScaleServiceServer) GetScale(context.Context, *GetScaleRequest) (*GetScaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScale not implemented")
}
func (UnimplementedScaleServiceServer) ListScales(context.Context, *ListScalesRequest) (*ListScalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScales not implemented")
}
func (UnimplementedScaleServiceServer) GetScaleCategories(context.Context, *GetScaleCategoriesRequest) (*GetScaleCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScaleCategories not implemented")
}
func (UnimplementedScaleServiceServer) mustEmbedUnimplementedScaleServiceServer() {}
func (UnimplementedScaleServiceServer) testEmbeddedByValue()                      {}

// UnsafeScaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScaleServiceServer will
// result in compilation errors.
type UnsafeScaleServiceServer interface {
	mustEmbedUnimplementedScaleServiceServer()
}

func RegisterScaleServiceServer(s grpc.ServiceRegistrar, srv ScaleServiceServer) {
	// If the following call pancis, it indicates UnimplementedScaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScaleService_ServiceDesc, srv)
}

func _ScaleService_GetScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScaleServiceServer).GetScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScaleService_GetScale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScaleServiceServer).GetScale(ctx, req.(*GetScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScaleService_ListScales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScaleServiceServer).ListScales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScaleService_ListScales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScaleServiceServer).ListScales(ctx, req.(*ListScalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScaleService_GetScaleCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScaleCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScaleServiceServer).GetScaleCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScaleService_GetScaleCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScaleServiceServer).GetScaleCategories(ctx, req.(*GetScaleCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScaleService_ServiceDesc is the grpc.ServiceDesc for ScaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scale.ScaleService",
	HandlerType: (*ScaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScale",
			Handler:    _ScaleService_GetScale_Handler,
		},
		{
			MethodName: "ListScales",
			Handler:    _ScaleService_ListScales_Handler,
		},
		{
			MethodName: "GetScaleCategories",
			Handler:    _ScaleService_GetScaleCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/apiserver/interface/grpc/proto/scale/scale.proto",
}
