// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internalapi/internal.proto

package internalapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalService_CalculateAnswerSheetScore_FullMethodName       = "/internalapi.InternalService/CalculateAnswerSheetScore"
	InternalService_CreateAssessmentFromAnswerSheet_FullMethodName = "/internalapi.InternalService/CreateAssessmentFromAnswerSheet"
	InternalService_EvaluateAssessment_FullMethodName              = "/internalapi.InternalService/EvaluateAssessment"
	InternalService_TagTestee_FullMethodName                       = "/internalapi.InternalService/TagTestee"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 内部服务 - 供 Worker 调用
// 用于事件处理后的业务逻辑调用
type InternalServiceClient interface {
	// 计算答卷分数
	// 场景：worker 处理 answersheet.submitted 事件后调用
	// 流程：根据问卷评分规则计算每个答案的分数并保存
	CalculateAnswerSheetScore(ctx context.Context, in *CalculateAnswerSheetScoreRequest, opts ...grpc.CallOption) (*CalculateAnswerSheetScoreResponse, error)
	// 从答卷创建测评
	// 场景：worker 处理 answersheet.submitted 事件后调用（在计分之后）
	// 流程：根据答卷信息创建 Assessment，如果问卷关联了量表则自动提交
	CreateAssessmentFromAnswerSheet(ctx context.Context, in *CreateAssessmentFromAnswerSheetRequest, opts ...grpc.CallOption) (*CreateAssessmentFromAnswerSheetResponse, error)
	// 执行测评评估
	// 场景：worker 处理 assessment.submitted 事件后调用
	// 流程：加载测评和量表，执行计分和解读，保存结果
	EvaluateAssessment(ctx context.Context, in *EvaluateAssessmentRequest, opts ...grpc.CallOption) (*EvaluateAssessmentResponse, error)
	// 给受试者打标签
	// 场景：worker 处理 report.generated 事件后调用
	// 流程：根据解读结果（风险等级、量表类型等）自动给受试者打标签
	TagTestee(ctx context.Context, in *TagTesteeRequest, opts ...grpc.CallOption) (*TagTesteeResponse, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) CalculateAnswerSheetScore(ctx context.Context, in *CalculateAnswerSheetScoreRequest, opts ...grpc.CallOption) (*CalculateAnswerSheetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateAnswerSheetScoreResponse)
	err := c.cc.Invoke(ctx, InternalService_CalculateAnswerSheetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) CreateAssessmentFromAnswerSheet(ctx context.Context, in *CreateAssessmentFromAnswerSheetRequest, opts ...grpc.CallOption) (*CreateAssessmentFromAnswerSheetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssessmentFromAnswerSheetResponse)
	err := c.cc.Invoke(ctx, InternalService_CreateAssessmentFromAnswerSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) EvaluateAssessment(ctx context.Context, in *EvaluateAssessmentRequest, opts ...grpc.CallOption) (*EvaluateAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateAssessmentResponse)
	err := c.cc.Invoke(ctx, InternalService_EvaluateAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) TagTestee(ctx context.Context, in *TagTesteeRequest, opts ...grpc.CallOption) (*TagTesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagTesteeResponse)
	err := c.cc.Invoke(ctx, InternalService_TagTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
//
// 内部服务 - 供 Worker 调用
// 用于事件处理后的业务逻辑调用
type InternalServiceServer interface {
	// 计算答卷分数
	// 场景：worker 处理 answersheet.submitted 事件后调用
	// 流程：根据问卷评分规则计算每个答案的分数并保存
	CalculateAnswerSheetScore(context.Context, *CalculateAnswerSheetScoreRequest) (*CalculateAnswerSheetScoreResponse, error)
	// 从答卷创建测评
	// 场景：worker 处理 answersheet.submitted 事件后调用（在计分之后）
	// 流程：根据答卷信息创建 Assessment，如果问卷关联了量表则自动提交
	CreateAssessmentFromAnswerSheet(context.Context, *CreateAssessmentFromAnswerSheetRequest) (*CreateAssessmentFromAnswerSheetResponse, error)
	// 执行测评评估
	// 场景：worker 处理 assessment.submitted 事件后调用
	// 流程：加载测评和量表，执行计分和解读，保存结果
	EvaluateAssessment(context.Context, *EvaluateAssessmentRequest) (*EvaluateAssessmentResponse, error)
	// 给受试者打标签
	// 场景：worker 处理 report.generated 事件后调用
	// 流程：根据解读结果（风险等级、量表类型等）自动给受试者打标签
	TagTestee(context.Context, *TagTesteeRequest) (*TagTesteeResponse, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) CalculateAnswerSheetScore(context.Context, *CalculateAnswerSheetScoreRequest) (*CalculateAnswerSheetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateAnswerSheetScore not implemented")
}
func (UnimplementedInternalServiceServer) CreateAssessmentFromAnswerSheet(context.Context, *CreateAssessmentFromAnswerSheetRequest) (*CreateAssessmentFromAnswerSheetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssessmentFromAnswerSheet not implemented")
}
func (UnimplementedInternalServiceServer) EvaluateAssessment(context.Context, *EvaluateAssessmentRequest) (*EvaluateAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateAssessment not implemented")
}
func (UnimplementedInternalServiceServer) TagTestee(context.Context, *TagTesteeRequest) (*TagTesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagTestee not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_CalculateAnswerSheetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAnswerSheetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).CalculateAnswerSheetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_CalculateAnswerSheetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).CalculateAnswerSheetScore(ctx, req.(*CalculateAnswerSheetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_CreateAssessmentFromAnswerSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentFromAnswerSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).CreateAssessmentFromAnswerSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_CreateAssessmentFromAnswerSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).CreateAssessmentFromAnswerSheet(ctx, req.(*CreateAssessmentFromAnswerSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_EvaluateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).EvaluateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_EvaluateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).EvaluateAssessment(ctx, req.(*EvaluateAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_TagTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).TagTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_TagTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).TagTestee(ctx, req.(*TagTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalapi.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateAnswerSheetScore",
			Handler:    _InternalService_CalculateAnswerSheetScore_Handler,
		},
		{
			MethodName: "CreateAssessmentFromAnswerSheet",
			Handler:    _InternalService_CreateAssessmentFromAnswerSheet_Handler,
		},
		{
			MethodName: "EvaluateAssessment",
			Handler:    _InternalService_EvaluateAssessment_Handler,
		},
		{
			MethodName: "TagTestee",
			Handler:    _InternalService_TagTestee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalapi/internal.proto",
}
