// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internalapi/internal.proto

package internalapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalService_CalculateAnswerSheetScore_FullMethodName             = "/internalapi.InternalService/CalculateAnswerSheetScore"
	InternalService_CreateAssessmentFromAnswerSheet_FullMethodName       = "/internalapi.InternalService/CreateAssessmentFromAnswerSheet"
	InternalService_EvaluateAssessment_FullMethodName                    = "/internalapi.InternalService/EvaluateAssessment"
	InternalService_TagTestee_FullMethodName                             = "/internalapi.InternalService/TagTestee"
	InternalService_GenerateQuestionnaireQRCode_FullMethodName           = "/internalapi.InternalService/GenerateQuestionnaireQRCode"
	InternalService_GenerateScaleQRCode_FullMethodName                   = "/internalapi.InternalService/GenerateScaleQRCode"
	InternalService_SendTaskOpenedMiniProgramNotification_FullMethodName = "/internalapi.InternalService/SendTaskOpenedMiniProgramNotification"
	InternalService_BootstrapOperator_FullMethodName                     = "/internalapi.InternalService/BootstrapOperator"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 内部服务 - 供 Worker 调用
// 用于事件处理后的业务逻辑调用
type InternalServiceClient interface {
	// 计算答卷分数
	// 场景：worker 处理 answersheet.submitted 事件后调用
	// 流程：根据问卷评分规则计算每个答案的分数并保存
	CalculateAnswerSheetScore(ctx context.Context, in *CalculateAnswerSheetScoreRequest, opts ...grpc.CallOption) (*CalculateAnswerSheetScoreResponse, error)
	// 从答卷创建测评
	// 场景：worker 处理 answersheet.submitted 事件后调用（在计分之后）
	// 流程：根据答卷信息创建 Assessment，如果问卷关联了量表则自动提交
	CreateAssessmentFromAnswerSheet(ctx context.Context, in *CreateAssessmentFromAnswerSheetRequest, opts ...grpc.CallOption) (*CreateAssessmentFromAnswerSheetResponse, error)
	// 执行测评评估
	// 场景：worker 处理 assessment.submitted 事件后调用
	// 流程：加载测评和量表，执行计分和解读，保存结果
	EvaluateAssessment(ctx context.Context, in *EvaluateAssessmentRequest, opts ...grpc.CallOption) (*EvaluateAssessmentResponse, error)
	// 给受试者打标签
	// 场景：worker 处理 report.generated 事件后调用
	// 流程：根据解读结果（风险等级、量表类型等）自动给受试者打标签
	TagTestee(ctx context.Context, in *TagTesteeRequest, opts ...grpc.CallOption) (*TagTesteeResponse, error)
	// 生成问卷小程序码
	// 场景：worker 处理 questionnaire.published 事件后调用
	// 流程：生成小程序码并保存，返回二维码 URL
	GenerateQuestionnaireQRCode(ctx context.Context, in *GenerateQuestionnaireQRCodeRequest, opts ...grpc.CallOption) (*GenerateQuestionnaireQRCodeResponse, error)
	// 生成量表小程序码
	// 场景：worker 处理 scale.published 事件后调用
	// 流程：生成小程序码并保存，返回二维码 URL
	GenerateScaleQRCode(ctx context.Context, in *GenerateScaleQRCodeRequest, opts ...grpc.CallOption) (*GenerateScaleQRCodeResponse, error)
	// 发送 task.opened 小程序订阅消息
	// 场景：worker 处理 task.opened 事件后调用
	// 流程：解析收件人（本人优先，监护人兜底）并发送小程序订阅消息
	SendTaskOpenedMiniProgramNotification(ctx context.Context, in *SendTaskOpenedMiniProgramNotificationRequest, opts ...grpc.CallOption) (*SendTaskOpenedMiniProgramNotificationResponse, error)
	// 自举首个操作者
	// 场景：seed/bootstrap 工具需要在尚无 active operator 的 org 中创建第一个 operator
	// 流程：EnsureByUser 幂等建档，同步基础信息，必要时激活/停用，并从 IAM 快照回填本地角色投影
	BootstrapOperator(ctx context.Context, in *BootstrapOperatorRequest, opts ...grpc.CallOption) (*BootstrapOperatorResponse, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) CalculateAnswerSheetScore(ctx context.Context, in *CalculateAnswerSheetScoreRequest, opts ...grpc.CallOption) (*CalculateAnswerSheetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateAnswerSheetScoreResponse)
	err := c.cc.Invoke(ctx, InternalService_CalculateAnswerSheetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) CreateAssessmentFromAnswerSheet(ctx context.Context, in *CreateAssessmentFromAnswerSheetRequest, opts ...grpc.CallOption) (*CreateAssessmentFromAnswerSheetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssessmentFromAnswerSheetResponse)
	err := c.cc.Invoke(ctx, InternalService_CreateAssessmentFromAnswerSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) EvaluateAssessment(ctx context.Context, in *EvaluateAssessmentRequest, opts ...grpc.CallOption) (*EvaluateAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateAssessmentResponse)
	err := c.cc.Invoke(ctx, InternalService_EvaluateAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) TagTestee(ctx context.Context, in *TagTesteeRequest, opts ...grpc.CallOption) (*TagTesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagTesteeResponse)
	err := c.cc.Invoke(ctx, InternalService_TagTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GenerateQuestionnaireQRCode(ctx context.Context, in *GenerateQuestionnaireQRCodeRequest, opts ...grpc.CallOption) (*GenerateQuestionnaireQRCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQuestionnaireQRCodeResponse)
	err := c.cc.Invoke(ctx, InternalService_GenerateQuestionnaireQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GenerateScaleQRCode(ctx context.Context, in *GenerateScaleQRCodeRequest, opts ...grpc.CallOption) (*GenerateScaleQRCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateScaleQRCodeResponse)
	err := c.cc.Invoke(ctx, InternalService_GenerateScaleQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) SendTaskOpenedMiniProgramNotification(ctx context.Context, in *SendTaskOpenedMiniProgramNotificationRequest, opts ...grpc.CallOption) (*SendTaskOpenedMiniProgramNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTaskOpenedMiniProgramNotificationResponse)
	err := c.cc.Invoke(ctx, InternalService_SendTaskOpenedMiniProgramNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) BootstrapOperator(ctx context.Context, in *BootstrapOperatorRequest, opts ...grpc.CallOption) (*BootstrapOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapOperatorResponse)
	err := c.cc.Invoke(ctx, InternalService_BootstrapOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
//
// 内部服务 - 供 Worker 调用
// 用于事件处理后的业务逻辑调用
type InternalServiceServer interface {
	// 计算答卷分数
	// 场景：worker 处理 answersheet.submitted 事件后调用
	// 流程：根据问卷评分规则计算每个答案的分数并保存
	CalculateAnswerSheetScore(context.Context, *CalculateAnswerSheetScoreRequest) (*CalculateAnswerSheetScoreResponse, error)
	// 从答卷创建测评
	// 场景：worker 处理 answersheet.submitted 事件后调用（在计分之后）
	// 流程：根据答卷信息创建 Assessment，如果问卷关联了量表则自动提交
	CreateAssessmentFromAnswerSheet(context.Context, *CreateAssessmentFromAnswerSheetRequest) (*CreateAssessmentFromAnswerSheetResponse, error)
	// 执行测评评估
	// 场景：worker 处理 assessment.submitted 事件后调用
	// 流程：加载测评和量表，执行计分和解读，保存结果
	EvaluateAssessment(context.Context, *EvaluateAssessmentRequest) (*EvaluateAssessmentResponse, error)
	// 给受试者打标签
	// 场景：worker 处理 report.generated 事件后调用
	// 流程：根据解读结果（风险等级、量表类型等）自动给受试者打标签
	TagTestee(context.Context, *TagTesteeRequest) (*TagTesteeResponse, error)
	// 生成问卷小程序码
	// 场景：worker 处理 questionnaire.published 事件后调用
	// 流程：生成小程序码并保存，返回二维码 URL
	GenerateQuestionnaireQRCode(context.Context, *GenerateQuestionnaireQRCodeRequest) (*GenerateQuestionnaireQRCodeResponse, error)
	// 生成量表小程序码
	// 场景：worker 处理 scale.published 事件后调用
	// 流程：生成小程序码并保存，返回二维码 URL
	GenerateScaleQRCode(context.Context, *GenerateScaleQRCodeRequest) (*GenerateScaleQRCodeResponse, error)
	// 发送 task.opened 小程序订阅消息
	// 场景：worker 处理 task.opened 事件后调用
	// 流程：解析收件人（本人优先，监护人兜底）并发送小程序订阅消息
	SendTaskOpenedMiniProgramNotification(context.Context, *SendTaskOpenedMiniProgramNotificationRequest) (*SendTaskOpenedMiniProgramNotificationResponse, error)
	// 自举首个操作者
	// 场景：seed/bootstrap 工具需要在尚无 active operator 的 org 中创建第一个 operator
	// 流程：EnsureByUser 幂等建档，同步基础信息，必要时激活/停用，并从 IAM 快照回填本地角色投影
	BootstrapOperator(context.Context, *BootstrapOperatorRequest) (*BootstrapOperatorResponse, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) CalculateAnswerSheetScore(context.Context, *CalculateAnswerSheetScoreRequest) (*CalculateAnswerSheetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateAnswerSheetScore not implemented")
}
func (UnimplementedInternalServiceServer) CreateAssessmentFromAnswerSheet(context.Context, *CreateAssessmentFromAnswerSheetRequest) (*CreateAssessmentFromAnswerSheetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssessmentFromAnswerSheet not implemented")
}
func (UnimplementedInternalServiceServer) EvaluateAssessment(context.Context, *EvaluateAssessmentRequest) (*EvaluateAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateAssessment not implemented")
}
func (UnimplementedInternalServiceServer) TagTestee(context.Context, *TagTesteeRequest) (*TagTesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagTestee not implemented")
}
func (UnimplementedInternalServiceServer) GenerateQuestionnaireQRCode(context.Context, *GenerateQuestionnaireQRCodeRequest) (*GenerateQuestionnaireQRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQuestionnaireQRCode not implemented")
}
func (UnimplementedInternalServiceServer) GenerateScaleQRCode(context.Context, *GenerateScaleQRCodeRequest) (*GenerateScaleQRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateScaleQRCode not implemented")
}
func (UnimplementedInternalServiceServer) SendTaskOpenedMiniProgramNotification(context.Context, *SendTaskOpenedMiniProgramNotificationRequest) (*SendTaskOpenedMiniProgramNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTaskOpenedMiniProgramNotification not implemented")
}
func (UnimplementedInternalServiceServer) BootstrapOperator(context.Context, *BootstrapOperatorRequest) (*BootstrapOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootstrapOperator not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_CalculateAnswerSheetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAnswerSheetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).CalculateAnswerSheetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_CalculateAnswerSheetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).CalculateAnswerSheetScore(ctx, req.(*CalculateAnswerSheetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_CreateAssessmentFromAnswerSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentFromAnswerSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).CreateAssessmentFromAnswerSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_CreateAssessmentFromAnswerSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).CreateAssessmentFromAnswerSheet(ctx, req.(*CreateAssessmentFromAnswerSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_EvaluateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).EvaluateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_EvaluateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).EvaluateAssessment(ctx, req.(*EvaluateAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_TagTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).TagTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_TagTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).TagTestee(ctx, req.(*TagTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GenerateQuestionnaireQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionnaireQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GenerateQuestionnaireQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GenerateQuestionnaireQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GenerateQuestionnaireQRCode(ctx, req.(*GenerateQuestionnaireQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GenerateScaleQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateScaleQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GenerateScaleQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GenerateScaleQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GenerateScaleQRCode(ctx, req.(*GenerateScaleQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_SendTaskOpenedMiniProgramNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTaskOpenedMiniProgramNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).SendTaskOpenedMiniProgramNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_SendTaskOpenedMiniProgramNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).SendTaskOpenedMiniProgramNotification(ctx, req.(*SendTaskOpenedMiniProgramNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_BootstrapOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).BootstrapOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_BootstrapOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).BootstrapOperator(ctx, req.(*BootstrapOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalapi.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateAnswerSheetScore",
			Handler:    _InternalService_CalculateAnswerSheetScore_Handler,
		},
		{
			MethodName: "CreateAssessmentFromAnswerSheet",
			Handler:    _InternalService_CreateAssessmentFromAnswerSheet_Handler,
		},
		{
			MethodName: "EvaluateAssessment",
			Handler:    _InternalService_EvaluateAssessment_Handler,
		},
		{
			MethodName: "TagTestee",
			Handler:    _InternalService_TagTestee_Handler,
		},
		{
			MethodName: "GenerateQuestionnaireQRCode",
			Handler:    _InternalService_GenerateQuestionnaireQRCode_Handler,
		},
		{
			MethodName: "GenerateScaleQRCode",
			Handler:    _InternalService_GenerateScaleQRCode_Handler,
		},
		{
			MethodName: "SendTaskOpenedMiniProgramNotification",
			Handler:    _InternalService_SendTaskOpenedMiniProgramNotification_Handler,
		},
		{
			MethodName: "BootstrapOperator",
			Handler:    _InternalService_BootstrapOperator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalapi/internal.proto",
}

const (
	PlanCommandService_CreatePlan_FullMethodName           = "/internalapi.PlanCommandService/CreatePlan"
	PlanCommandService_PausePlan_FullMethodName            = "/internalapi.PlanCommandService/PausePlan"
	PlanCommandService_ResumePlan_FullMethodName           = "/internalapi.PlanCommandService/ResumePlan"
	PlanCommandService_CancelPlan_FullMethodName           = "/internalapi.PlanCommandService/CancelPlan"
	PlanCommandService_EnrollTestee_FullMethodName         = "/internalapi.PlanCommandService/EnrollTestee"
	PlanCommandService_TerminateEnrollment_FullMethodName  = "/internalapi.PlanCommandService/TerminateEnrollment"
	PlanCommandService_SchedulePendingTasks_FullMethodName = "/internalapi.PlanCommandService/SchedulePendingTasks"
	PlanCommandService_OpenTask_FullMethodName             = "/internalapi.PlanCommandService/OpenTask"
	PlanCommandService_CompleteTask_FullMethodName         = "/internalapi.PlanCommandService/CompleteTask"
	PlanCommandService_ExpireTask_FullMethodName           = "/internalapi.PlanCommandService/ExpireTask"
	PlanCommandService_CancelTask_FullMethodName           = "/internalapi.PlanCommandService/CancelTask"
)

// PlanCommandServiceClient is the client API for PlanCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plan 写侧命令服务 - 供 Worker 和内部系统动作调用
type PlanCommandServiceClient interface {
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error)
	PausePlan(ctx context.Context, in *PausePlanRequest, opts ...grpc.CallOption) (*PausePlanResponse, error)
	ResumePlan(ctx context.Context, in *ResumePlanRequest, opts ...grpc.CallOption) (*ResumePlanResponse, error)
	CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error)
	EnrollTestee(ctx context.Context, in *EnrollTesteeRequest, opts ...grpc.CallOption) (*EnrollTesteeResponse, error)
	TerminateEnrollment(ctx context.Context, in *TerminateEnrollmentRequest, opts ...grpc.CallOption) (*TerminateEnrollmentResponse, error)
	SchedulePendingTasks(ctx context.Context, in *SchedulePendingTasksRequest, opts ...grpc.CallOption) (*SchedulePendingTasksResponse, error)
	OpenTask(ctx context.Context, in *OpenTaskRequest, opts ...grpc.CallOption) (*OpenTaskResponse, error)
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	ExpireTask(ctx context.Context, in *ExpireTaskRequest, opts ...grpc.CallOption) (*ExpireTaskResponse, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
}

type planCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanCommandServiceClient(cc grpc.ClientConnInterface) PlanCommandServiceClient {
	return &planCommandServiceClient{cc}
}

func (c *planCommandServiceClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) PausePlan(ctx context.Context, in *PausePlanRequest, opts ...grpc.CallOption) (*PausePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PausePlanResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_PausePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) ResumePlan(ctx context.Context, in *ResumePlanRequest, opts ...grpc.CallOption) (*ResumePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumePlanResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_ResumePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPlanResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_CancelPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) EnrollTestee(ctx context.Context, in *EnrollTesteeRequest, opts ...grpc.CallOption) (*EnrollTesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollTesteeResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_EnrollTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) TerminateEnrollment(ctx context.Context, in *TerminateEnrollmentRequest, opts ...grpc.CallOption) (*TerminateEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateEnrollmentResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_TerminateEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) SchedulePendingTasks(ctx context.Context, in *SchedulePendingTasksRequest, opts ...grpc.CallOption) (*SchedulePendingTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulePendingTasksResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_SchedulePendingTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) OpenTask(ctx context.Context, in *OpenTaskRequest, opts ...grpc.CallOption) (*OpenTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTaskResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_OpenTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) ExpireTask(ctx context.Context, in *ExpireTaskRequest, opts ...grpc.CallOption) (*ExpireTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireTaskResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_ExpireTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planCommandServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, PlanCommandService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanCommandServiceServer is the server API for PlanCommandService service.
// All implementations must embed UnimplementedPlanCommandServiceServer
// for forward compatibility.
//
// Plan 写侧命令服务 - 供 Worker 和内部系统动作调用
type PlanCommandServiceServer interface {
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error)
	PausePlan(context.Context, *PausePlanRequest) (*PausePlanResponse, error)
	ResumePlan(context.Context, *ResumePlanRequest) (*ResumePlanResponse, error)
	CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error)
	EnrollTestee(context.Context, *EnrollTesteeRequest) (*EnrollTesteeResponse, error)
	TerminateEnrollment(context.Context, *TerminateEnrollmentRequest) (*TerminateEnrollmentResponse, error)
	SchedulePendingTasks(context.Context, *SchedulePendingTasksRequest) (*SchedulePendingTasksResponse, error)
	OpenTask(context.Context, *OpenTaskRequest) (*OpenTaskResponse, error)
	CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error)
	ExpireTask(context.Context, *ExpireTaskRequest) (*ExpireTaskResponse, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	mustEmbedUnimplementedPlanCommandServiceServer()
}

// UnimplementedPlanCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanCommandServiceServer struct{}

func (UnimplementedPlanCommandServiceServer) CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedPlanCommandServiceServer) PausePlan(context.Context, *PausePlanRequest) (*PausePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PausePlan not implemented")
}
func (UnimplementedPlanCommandServiceServer) ResumePlan(context.Context, *ResumePlanRequest) (*ResumePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumePlan not implemented")
}
func (UnimplementedPlanCommandServiceServer) CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPlan not implemented")
}
func (UnimplementedPlanCommandServiceServer) EnrollTestee(context.Context, *EnrollTesteeRequest) (*EnrollTesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollTestee not implemented")
}
func (UnimplementedPlanCommandServiceServer) TerminateEnrollment(context.Context, *TerminateEnrollmentRequest) (*TerminateEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateEnrollment not implemented")
}
func (UnimplementedPlanCommandServiceServer) SchedulePendingTasks(context.Context, *SchedulePendingTasksRequest) (*SchedulePendingTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulePendingTasks not implemented")
}
func (UnimplementedPlanCommandServiceServer) OpenTask(context.Context, *OpenTaskRequest) (*OpenTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTask not implemented")
}
func (UnimplementedPlanCommandServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedPlanCommandServiceServer) ExpireTask(context.Context, *ExpireTaskRequest) (*ExpireTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireTask not implemented")
}
func (UnimplementedPlanCommandServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedPlanCommandServiceServer) mustEmbedUnimplementedPlanCommandServiceServer() {}
func (UnimplementedPlanCommandServiceServer) testEmbeddedByValue()                            {}

// UnsafePlanCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanCommandServiceServer will
// result in compilation errors.
type UnsafePlanCommandServiceServer interface {
	mustEmbedUnimplementedPlanCommandServiceServer()
}

func RegisterPlanCommandServiceServer(s grpc.ServiceRegistrar, srv PlanCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlanCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanCommandService_ServiceDesc, srv)
}

func _PlanCommandService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_PausePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PausePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).PausePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_PausePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).PausePlan(ctx, req.(*PausePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_ResumePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).ResumePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_ResumePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).ResumePlan(ctx, req.(*ResumePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_CancelPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).CancelPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_CancelPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).CancelPlan(ctx, req.(*CancelPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_EnrollTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).EnrollTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_EnrollTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).EnrollTestee(ctx, req.(*EnrollTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_TerminateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).TerminateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_TerminateEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).TerminateEnrollment(ctx, req.(*TerminateEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_SchedulePendingTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePendingTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).SchedulePendingTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_SchedulePendingTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).SchedulePendingTasks(ctx, req.(*SchedulePendingTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_OpenTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).OpenTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_OpenTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).OpenTask(ctx, req.(*OpenTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_ExpireTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).ExpireTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_ExpireTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).ExpireTask(ctx, req.(*ExpireTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanCommandService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanCommandServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanCommandService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanCommandServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanCommandService_ServiceDesc is the grpc.ServiceDesc for PlanCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalapi.PlanCommandService",
	HandlerType: (*PlanCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _PlanCommandService_CreatePlan_Handler,
		},
		{
			MethodName: "PausePlan",
			Handler:    _PlanCommandService_PausePlan_Handler,
		},
		{
			MethodName: "ResumePlan",
			Handler:    _PlanCommandService_ResumePlan_Handler,
		},
		{
			MethodName: "CancelPlan",
			Handler:    _PlanCommandService_CancelPlan_Handler,
		},
		{
			MethodName: "EnrollTestee",
			Handler:    _PlanCommandService_EnrollTestee_Handler,
		},
		{
			MethodName: "TerminateEnrollment",
			Handler:    _PlanCommandService_TerminateEnrollment_Handler,
		},
		{
			MethodName: "SchedulePendingTasks",
			Handler:    _PlanCommandService_SchedulePendingTasks_Handler,
		},
		{
			MethodName: "OpenTask",
			Handler:    _PlanCommandService_OpenTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _PlanCommandService_CompleteTask_Handler,
		},
		{
			MethodName: "ExpireTask",
			Handler:    _PlanCommandService_ExpireTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _PlanCommandService_CancelTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalapi/internal.proto",
}
