// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internalapi/internal.proto

package internalapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 计算答卷分数请求
type CalculateAnswerSheetScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswersheetId uint64                 `protobuf:"varint,1,opt,name=answersheet_id,json=answersheetId,proto3" json:"answersheet_id,omitempty"` // 答卷ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateAnswerSheetScoreRequest) Reset() {
	*x = CalculateAnswerSheetScoreRequest{}
	mi := &file_internalapi_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateAnswerSheetScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAnswerSheetScoreRequest) ProtoMessage() {}

func (x *CalculateAnswerSheetScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAnswerSheetScoreRequest.ProtoReflect.Descriptor instead.
func (*CalculateAnswerSheetScoreRequest) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateAnswerSheetScoreRequest) GetAnswersheetId() uint64 {
	if x != nil {
		return x.AnswersheetId
	}
	return 0
}

// 计算答卷分数响应
type CalculateAnswerSheetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                          // 是否成功
	TotalScore    float64                `protobuf:"fixed64,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"` // 总分
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                           // 描述信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateAnswerSheetScoreResponse) Reset() {
	*x = CalculateAnswerSheetScoreResponse{}
	mi := &file_internalapi_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateAnswerSheetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAnswerSheetScoreResponse) ProtoMessage() {}

func (x *CalculateAnswerSheetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAnswerSheetScoreResponse.ProtoReflect.Descriptor instead.
func (*CalculateAnswerSheetScoreResponse) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateAnswerSheetScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculateAnswerSheetScoreResponse) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *CalculateAnswerSheetScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 从答卷创建测评请求
type CreateAssessmentFromAnswerSheetRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AnswersheetId        uint64                 `protobuf:"varint,1,opt,name=answersheet_id,json=answersheetId,proto3" json:"answersheet_id,omitempty"`                     // 答卷ID
	QuestionnaireCode    string                 `protobuf:"bytes,2,opt,name=questionnaire_code,json=questionnaireCode,proto3" json:"questionnaire_code,omitempty"`          // 问卷编码
	QuestionnaireVersion string                 `protobuf:"bytes,3,opt,name=questionnaire_version,json=questionnaireVersion,proto3" json:"questionnaire_version,omitempty"` // 问卷版本
	TesteeId             uint64                 `protobuf:"varint,4,opt,name=testee_id,json=testeeId,proto3" json:"testee_id,omitempty"`                                    // 受试者ID
	OrgId                uint64                 `protobuf:"varint,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                                             // 组织ID
	FillerId             uint64                 `protobuf:"varint,6,opt,name=filler_id,json=fillerId,proto3" json:"filler_id,omitempty"`                                    // 填写人ID
	FillerType           string                 `protobuf:"bytes,7,opt,name=filler_type,json=fillerType,proto3" json:"filler_type,omitempty"`                               // 填写人类型：self/proxy
	OriginType           string                 `protobuf:"bytes,8,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`                               // 来源类型：adhoc/plan/screening（可选）
	OriginId             string                 `protobuf:"bytes,9,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`                                     // 来源ID（可选）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAssessmentFromAnswerSheetRequest) Reset() {
	*x = CreateAssessmentFromAnswerSheetRequest{}
	mi := &file_internalapi_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssessmentFromAnswerSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssessmentFromAnswerSheetRequest) ProtoMessage() {}

func (x *CreateAssessmentFromAnswerSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssessmentFromAnswerSheetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssessmentFromAnswerSheetRequest) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetAnswersheetId() uint64 {
	if x != nil {
		return x.AnswersheetId
	}
	return 0
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetQuestionnaireCode() string {
	if x != nil {
		return x.QuestionnaireCode
	}
	return ""
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetQuestionnaireVersion() string {
	if x != nil {
		return x.QuestionnaireVersion
	}
	return ""
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetTesteeId() uint64 {
	if x != nil {
		return x.TesteeId
	}
	return 0
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetFillerId() uint64 {
	if x != nil {
		return x.FillerId
	}
	return 0
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetFillerType() string {
	if x != nil {
		return x.FillerType
	}
	return ""
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *CreateAssessmentFromAnswerSheetRequest) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

// 从答卷创建测评响应
type CreateAssessmentFromAnswerSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  uint64                 `protobuf:"varint,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`    // 创建的测评ID（如果有）
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`                                  // 是否创建了测评
	AutoSubmitted bool                   `protobuf:"varint,3,opt,name=auto_submitted,json=autoSubmitted,proto3" json:"auto_submitted,omitempty"` // 是否自动提交（关联量表时）
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                   // 描述信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssessmentFromAnswerSheetResponse) Reset() {
	*x = CreateAssessmentFromAnswerSheetResponse{}
	mi := &file_internalapi_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssessmentFromAnswerSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssessmentFromAnswerSheetResponse) ProtoMessage() {}

func (x *CreateAssessmentFromAnswerSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssessmentFromAnswerSheetResponse.ProtoReflect.Descriptor instead.
func (*CreateAssessmentFromAnswerSheetResponse) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAssessmentFromAnswerSheetResponse) GetAssessmentId() uint64 {
	if x != nil {
		return x.AssessmentId
	}
	return 0
}

func (x *CreateAssessmentFromAnswerSheetResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateAssessmentFromAnswerSheetResponse) GetAutoSubmitted() bool {
	if x != nil {
		return x.AutoSubmitted
	}
	return false
}

func (x *CreateAssessmentFromAnswerSheetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 执行测评评估请求
type EvaluateAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  uint64                 `protobuf:"varint,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"` // 测评ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAssessmentRequest) Reset() {
	*x = EvaluateAssessmentRequest{}
	mi := &file_internalapi_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAssessmentRequest) ProtoMessage() {}

func (x *EvaluateAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAssessmentRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateAssessmentRequest) GetAssessmentId() uint64 {
	if x != nil {
		return x.AssessmentId
	}
	return 0
}

// 执行测评评估响应
type EvaluateAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                          // 是否成功
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                             // 处理后的状态：interpreted/failed/skipped
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                           // 描述信息
	TotalScore    float64                `protobuf:"fixed64,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"` // 总分（成功时）
	RiskLevel     string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`      // 风险等级（成功时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAssessmentResponse) Reset() {
	*x = EvaluateAssessmentResponse{}
	mi := &file_internalapi_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAssessmentResponse) ProtoMessage() {}

func (x *EvaluateAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalapi_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAssessmentResponse.ProtoReflect.Descriptor instead.
func (*EvaluateAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_internalapi_internal_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateAssessmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EvaluateAssessmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvaluateAssessmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EvaluateAssessmentResponse) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *EvaluateAssessmentResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

var File_internalapi_internal_proto protoreflect.FileDescriptor

const file_internalapi_internal_proto_rawDesc = "" +
	"\n" +
	"\x1ainternalapi/internal.proto\x12\vinternalapi\"I\n" +
	" CalculateAnswerSheetScoreRequest\x12%\n" +
	"\x0eanswersheet_id\x18\x01 \x01(\x04R\ranswersheetId\"x\n" +
	"!CalculateAnswerSheetScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\x01R\n" +
	"totalScore\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe3\x02\n" +
	"&CreateAssessmentFromAnswerSheetRequest\x12%\n" +
	"\x0eanswersheet_id\x18\x01 \x01(\x04R\ranswersheetId\x12-\n" +
	"\x12questionnaire_code\x18\x02 \x01(\tR\x11questionnaireCode\x123\n" +
	"\x15questionnaire_version\x18\x03 \x01(\tR\x14questionnaireVersion\x12\x1b\n" +
	"\ttestee_id\x18\x04 \x01(\x04R\btesteeId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\x04R\x05orgId\x12\x1b\n" +
	"\tfiller_id\x18\x06 \x01(\x04R\bfillerId\x12\x1f\n" +
	"\vfiller_type\x18\a \x01(\tR\n" +
	"fillerType\x12\x1f\n" +
	"\vorigin_type\x18\b \x01(\tR\n" +
	"originType\x12\x1b\n" +
	"\torigin_id\x18\t \x01(\tR\boriginId\"\xa9\x01\n" +
	"'CreateAssessmentFromAnswerSheetResponse\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\x04R\fassessmentId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12%\n" +
	"\x0eauto_submitted\x18\x03 \x01(\bR\rautoSubmitted\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"@\n" +
	"\x19EvaluateAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\x04R\fassessmentId\"\xa8\x01\n" +
	"\x1aEvaluateAssessmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vtotal_score\x18\x04 \x01(\x01R\n" +
	"totalScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel2\x83\x03\n" +
	"\x0fInternalService\x12z\n" +
	"\x19CalculateAnswerSheetScore\x12-.internalapi.CalculateAnswerSheetScoreRequest\x1a..internalapi.CalculateAnswerSheetScoreResponse\x12\x8c\x01\n" +
	"\x1fCreateAssessmentFromAnswerSheet\x123.internalapi.CreateAssessmentFromAnswerSheetRequest\x1a4.internalapi.CreateAssessmentFromAnswerSheetResponse\x12e\n" +
	"\x12EvaluateAssessment\x12&.internalapi.EvaluateAssessmentRequest\x1a'.internalapi.EvaluateAssessmentResponseBWZUgithub.com/FangcunMount/qs-server/internal/apiserver/interface/grpc/proto/internalapib\x06proto3"

var (
	file_internalapi_internal_proto_rawDescOnce sync.Once
	file_internalapi_internal_proto_rawDescData []byte
)

func file_internalapi_internal_proto_rawDescGZIP() []byte {
	file_internalapi_internal_proto_rawDescOnce.Do(func() {
		file_internalapi_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internalapi_internal_proto_rawDesc), len(file_internalapi_internal_proto_rawDesc)))
	})
	return file_internalapi_internal_proto_rawDescData
}

var file_internalapi_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internalapi_internal_proto_goTypes = []any{
	(*CalculateAnswerSheetScoreRequest)(nil),        // 0: internalapi.CalculateAnswerSheetScoreRequest
	(*CalculateAnswerSheetScoreResponse)(nil),       // 1: internalapi.CalculateAnswerSheetScoreResponse
	(*CreateAssessmentFromAnswerSheetRequest)(nil),  // 2: internalapi.CreateAssessmentFromAnswerSheetRequest
	(*CreateAssessmentFromAnswerSheetResponse)(nil), // 3: internalapi.CreateAssessmentFromAnswerSheetResponse
	(*EvaluateAssessmentRequest)(nil),               // 4: internalapi.EvaluateAssessmentRequest
	(*EvaluateAssessmentResponse)(nil),              // 5: internalapi.EvaluateAssessmentResponse
}
var file_internalapi_internal_proto_depIdxs = []int32{
	0, // 0: internalapi.InternalService.CalculateAnswerSheetScore:input_type -> internalapi.CalculateAnswerSheetScoreRequest
	2, // 1: internalapi.InternalService.CreateAssessmentFromAnswerSheet:input_type -> internalapi.CreateAssessmentFromAnswerSheetRequest
	4, // 2: internalapi.InternalService.EvaluateAssessment:input_type -> internalapi.EvaluateAssessmentRequest
	1, // 3: internalapi.InternalService.CalculateAnswerSheetScore:output_type -> internalapi.CalculateAnswerSheetScoreResponse
	3, // 4: internalapi.InternalService.CreateAssessmentFromAnswerSheet:output_type -> internalapi.CreateAssessmentFromAnswerSheetResponse
	5, // 5: internalapi.InternalService.EvaluateAssessment:output_type -> internalapi.EvaluateAssessmentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internalapi_internal_proto_init() }
func file_internalapi_internal_proto_init() {
	if File_internalapi_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internalapi_internal_proto_rawDesc), len(file_internalapi_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internalapi_internal_proto_goTypes,
		DependencyIndexes: file_internalapi_internal_proto_depIdxs,
		MessageInfos:      file_internalapi_internal_proto_msgTypes,
	}.Build()
	File_internalapi_internal_proto = out.File
	file_internalapi_internal_proto_goTypes = nil
	file_internalapi_internal_proto_depIdxs = nil
}
