// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: questionnaire/questionnaire.proto

package questionnaire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 问卷摘要信息（用于列表查询，不含 questions）
type QuestionnaireSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,4,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	QuestionCount int32                  `protobuf:"varint,7,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionnaireSummary) Reset() {
	*x = QuestionnaireSummary{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionnaireSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionnaireSummary) ProtoMessage() {}

func (x *QuestionnaireSummary) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionnaireSummary.ProtoReflect.Descriptor instead.
func (*QuestionnaireSummary) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionnaireSummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QuestionnaireSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionnaireSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestionnaireSummary) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *QuestionnaireSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QuestionnaireSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *QuestionnaireSummary) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *QuestionnaireSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QuestionnaireSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 问卷完整信息（用于详情查询）
type Questionnaire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,4,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Questions     []*Question            `protobuf:"bytes,7,rep,name=questions,proto3" json:"questions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Questionnaire) Reset() {
	*x = Questionnaire{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Questionnaire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Questionnaire) ProtoMessage() {}

func (x *Questionnaire) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Questionnaire.ProtoReflect.Descriptor instead.
func (*Questionnaire) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{1}
}

func (x *Questionnaire) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Questionnaire) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Questionnaire) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Questionnaire) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *Questionnaire) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Questionnaire) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Questionnaire) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Questionnaire) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Questionnaire) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 问题信息
type Question struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Tips            string                 `protobuf:"bytes,4,opt,name=tips,proto3" json:"tips,omitempty"`
	Placeholder     string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Options         []*Option              `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	ValidationRules []*ValidationRule      `protobuf:"bytes,7,rep,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	CalculationRule *CalculationRule       `protobuf:"bytes,8,opt,name=calculation_rule,json=calculationRule,proto3" json:"calculation_rule,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

func (x *Question) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Question) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetValidationRules() []*ValidationRule {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

func (x *Question) GetCalculationRule() *CalculationRule {
	if x != nil {
		return x.CalculationRule
	}
	return nil
}

// 选项信息
type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{3}
}

func (x *Option) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Option) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Option) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 验证规则
type ValidationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleType      string                 `protobuf:"bytes,1,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	TargetValue   string                 `protobuf:"bytes,2,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRule) Reset() {
	*x = ValidationRule{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRule) ProtoMessage() {}

func (x *ValidationRule) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRule.ProtoReflect.Descriptor instead.
func (*ValidationRule) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *ValidationRule) GetTargetValue() string {
	if x != nil {
		return x.TargetValue
	}
	return ""
}

// 计算规则
type CalculationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormulaType   string                 `protobuf:"bytes,1,opt,name=formula_type,json=formulaType,proto3" json:"formula_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRule) Reset() {
	*x = CalculationRule{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRule) ProtoMessage() {}

func (x *CalculationRule) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRule.ProtoReflect.Descriptor instead.
func (*CalculationRule) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{5}
}

func (x *CalculationRule) GetFormulaType() string {
	if x != nil {
		return x.FormulaType
	}
	return ""
}

// 获取问卷请求
type GetQuestionnaireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionnaireRequest) Reset() {
	*x = GetQuestionnaireRequest{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireRequest) ProtoMessage() {}

func (x *GetQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{6}
}

func (x *GetQuestionnaireRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 获取问卷响应
type GetQuestionnaireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questionnaire *Questionnaire         `protobuf:"bytes,1,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionnaireResponse) Reset() {
	*x = GetQuestionnaireResponse{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionnaireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireResponse) ProtoMessage() {}

func (x *GetQuestionnaireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireResponse) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuestionnaireResponse) GetQuestionnaire() *Questionnaire {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

// 获取问卷列表请求
type ListQuestionnairesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionnairesRequest) Reset() {
	*x = ListQuestionnairesRequest{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionnairesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionnairesRequest) ProtoMessage() {}

func (x *ListQuestionnairesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionnairesRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionnairesRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{8}
}

func (x *ListQuestionnairesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListQuestionnairesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListQuestionnairesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListQuestionnairesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// 获取问卷列表响应（返回摘要，不含 questions）
type ListQuestionnairesResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Questionnaires []*QuestionnaireSummary `protobuf:"bytes,1,rep,name=questionnaires,proto3" json:"questionnaires,omitempty"`
	Total          int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListQuestionnairesResponse) Reset() {
	*x = ListQuestionnairesResponse{}
	mi := &file_questionnaire_questionnaire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionnairesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionnairesResponse) ProtoMessage() {}

func (x *ListQuestionnairesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_questionnaire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionnairesResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionnairesResponse) Descriptor() ([]byte, []int) {
	return file_questionnaire_questionnaire_proto_rawDescGZIP(), []int{9}
}

func (x *ListQuestionnairesResponse) GetQuestionnaires() []*QuestionnaireSummary {
	if x != nil {
		return x.Questionnaires
	}
	return nil
}

func (x *ListQuestionnairesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_questionnaire_questionnaire_proto protoreflect.FileDescriptor

const file_questionnaire_questionnaire_proto_rawDesc = "" +
	"\n" +
	"!questionnaire/questionnaire.proto\x12\rquestionnaire\"\x92\x02\n" +
	"\x14QuestionnaireSummary\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\aimg_url\x18\x04 \x01(\tR\x06imgUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12%\n" +
	"\x0equestion_count\x18\a \x01(\x05R\rquestionCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x9b\x02\n" +
	"\rQuestionnaire\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\aimg_url\x18\x04 \x01(\tR\x06imgUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x125\n" +
	"\tquestions\x18\a \x03(\v2\x17.questionnaire.QuestionR\tquestions\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xc4\x02\n" +
	"\bQuestion\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04tips\x18\x04 \x01(\tR\x04tips\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12/\n" +
	"\aoptions\x18\x06 \x03(\v2\x15.questionnaire.OptionR\aoptions\x12H\n" +
	"\x10validation_rules\x18\a \x03(\v2\x1d.questionnaire.ValidationRuleR\x0fvalidationRules\x12I\n" +
	"\x10calculation_rule\x18\b \x01(\v2\x1e.questionnaire.CalculationRuleR\x0fcalculationRule\"L\n" +
	"\x06Option\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"P\n" +
	"\x0eValidationRule\x12\x1b\n" +
	"\trule_type\x18\x01 \x01(\tR\bruleType\x12!\n" +
	"\ftarget_value\x18\x02 \x01(\tR\vtargetValue\"4\n" +
	"\x0fCalculationRule\x12!\n" +
	"\fformula_type\x18\x01 \x01(\tR\vformulaType\"-\n" +
	"\x17GetQuestionnaireRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"^\n" +
	"\x18GetQuestionnaireResponse\x12B\n" +
	"\rquestionnaire\x18\x01 \x01(\v2\x1c.questionnaire.QuestionnaireR\rquestionnaire\"z\n" +
	"\x19ListQuestionnairesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\x7f\n" +
	"\x1aListQuestionnairesResponse\x12K\n" +
	"\x0equestionnaires\x18\x01 \x03(\v2#.questionnaire.QuestionnaireSummaryR\x0equestionnaires\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xe6\x01\n" +
	"\x14QuestionnaireService\x12c\n" +
	"\x10GetQuestionnaire\x12&.questionnaire.GetQuestionnaireRequest\x1a'.questionnaire.GetQuestionnaireResponse\x12i\n" +
	"\x12ListQuestionnaires\x12(.questionnaire.ListQuestionnairesRequest\x1a).questionnaire.ListQuestionnairesResponseB^Z\\github.com/yshujie/questionnaire-scale/internal/apiserver/interface/grpc/proto/questionnaireb\x06proto3"

var (
	file_questionnaire_questionnaire_proto_rawDescOnce sync.Once
	file_questionnaire_questionnaire_proto_rawDescData []byte
)

func file_questionnaire_questionnaire_proto_rawDescGZIP() []byte {
	file_questionnaire_questionnaire_proto_rawDescOnce.Do(func() {
		file_questionnaire_questionnaire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_questionnaire_questionnaire_proto_rawDesc), len(file_questionnaire_questionnaire_proto_rawDesc)))
	})
	return file_questionnaire_questionnaire_proto_rawDescData
}

var file_questionnaire_questionnaire_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_questionnaire_questionnaire_proto_goTypes = []any{
	(*QuestionnaireSummary)(nil),       // 0: questionnaire.QuestionnaireSummary
	(*Questionnaire)(nil),              // 1: questionnaire.Questionnaire
	(*Question)(nil),                   // 2: questionnaire.Question
	(*Option)(nil),                     // 3: questionnaire.Option
	(*ValidationRule)(nil),             // 4: questionnaire.ValidationRule
	(*CalculationRule)(nil),            // 5: questionnaire.CalculationRule
	(*GetQuestionnaireRequest)(nil),    // 6: questionnaire.GetQuestionnaireRequest
	(*GetQuestionnaireResponse)(nil),   // 7: questionnaire.GetQuestionnaireResponse
	(*ListQuestionnairesRequest)(nil),  // 8: questionnaire.ListQuestionnairesRequest
	(*ListQuestionnairesResponse)(nil), // 9: questionnaire.ListQuestionnairesResponse
}
var file_questionnaire_questionnaire_proto_depIdxs = []int32{
	2, // 0: questionnaire.Questionnaire.questions:type_name -> questionnaire.Question
	3, // 1: questionnaire.Question.options:type_name -> questionnaire.Option
	4, // 2: questionnaire.Question.validation_rules:type_name -> questionnaire.ValidationRule
	5, // 3: questionnaire.Question.calculation_rule:type_name -> questionnaire.CalculationRule
	1, // 4: questionnaire.GetQuestionnaireResponse.questionnaire:type_name -> questionnaire.Questionnaire
	0, // 5: questionnaire.ListQuestionnairesResponse.questionnaires:type_name -> questionnaire.QuestionnaireSummary
	6, // 6: questionnaire.QuestionnaireService.GetQuestionnaire:input_type -> questionnaire.GetQuestionnaireRequest
	8, // 7: questionnaire.QuestionnaireService.ListQuestionnaires:input_type -> questionnaire.ListQuestionnairesRequest
	7, // 8: questionnaire.QuestionnaireService.GetQuestionnaire:output_type -> questionnaire.GetQuestionnaireResponse
	9, // 9: questionnaire.QuestionnaireService.ListQuestionnaires:output_type -> questionnaire.ListQuestionnairesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_questionnaire_questionnaire_proto_init() }
func file_questionnaire_questionnaire_proto_init() {
	if File_questionnaire_questionnaire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_questionnaire_questionnaire_proto_rawDesc), len(file_questionnaire_questionnaire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_questionnaire_questionnaire_proto_goTypes,
		DependencyIndexes: file_questionnaire_questionnaire_proto_depIdxs,
		MessageInfos:      file_questionnaire_questionnaire_proto_msgTypes,
	}.Build()
	File_questionnaire_questionnaire_proto = out.File
	file_questionnaire_questionnaire_proto_goTypes = nil
	file_questionnaire_questionnaire_proto_depIdxs = nil
}
