#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=/dev/null
. "$SCRIPT_DIR/image-metadata.sh"

require_env() {
  local missing=0
  local var
  for var in "$@"; do
    if [ -z "${!var:-}" ]; then
      echo "Missing required env: $var" >&2
      missing=1
    fi
  done
  if [ "$missing" -ne 0 ]; then
    exit 1
  fi
}

default_redis_ssl() {
  REDIS_DB="${REDIS_DB:-0}"
  if [ -z "${REDIS_USE_SSL:-}" ]; then
    if [ "${REDIS_PORT:-}" = "6380" ]; then
      REDIS_USE_SSL=true
    else
      REDIS_USE_SSL=false
    fi
  fi
  REDIS_SSL_INSECURE_SKIP_VERIFY="${REDIS_SSL_INSECURE_SKIP_VERIFY:-false}"
}

redact_env_file() {
  sed \
    -e 's/PASSWORD=.*/PASSWORD=***REDACTED***/g' \
    -e 's/SECRET=.*/SECRET=***REDACTED***/g' \
    -e 's/ACCESS_KEY_ID=.*/ACCESS_KEY_ID=***REDACTED***/g' \
    -e 's/SESSION_TOKEN=.*/SESSION_TOKEN=***REDACTED***/g' \
    "$1"
}

PACKAGE_DIR="${DEPLOY_PACKAGE_DIR:-deploy-package}"
ENV_FILE="${PACKAGE_DIR}/configs/env/config.prod.env"

rm -rf "$PACKAGE_DIR" "$DEPLOY_PACKAGE"
mkdir -p "${PACKAGE_DIR}/configs/env" "${PACKAGE_DIR}/scripts/cd"
cp -r configs "$PACKAGE_DIR/"
cp build/docker/docker-compose.prod.yml "${PACKAGE_DIR}/docker-compose.prod.yml"
cp scripts/cd/image-metadata.sh scripts/cd/remote-deploy.sh "${PACKAGE_DIR}/scripts/cd/"

case "$SERVICE" in
  apiserver)
    MONGODB_PORT="${MONGODB_PORT:-27017}"
    MYSQL_PORT="${MYSQL_PORT:-3306}"
    REDIS_PORT="${REDIS_PORT:-6379}"
    NSQ_NSQD_PORT="${NSQ_NSQD_PORT:-4150}"
    default_redis_ssl
    require_env \
      MONGODB_HOST MONGODB_PORT MONGODB_USERNAME MONGODB_PASSWORD MONGODB_DBNAME \
      MYSQL_HOST MYSQL_PORT MYSQL_USERNAME MYSQL_PASSWORD MYSQL_DATABASE \
      REDIS_HOST REDIS_PORT JWT_SECRET NSQ_NSQD_HOST NSQ_NSQD_PORT \
      OSS_ACCESS_KEY_ID OSS_ACCESS_KEY_SECRET

    cat > "$ENV_FILE" <<EOF
# Auto-generated production environment configuration for QS API Server
# MongoDB split parameter configuration.
QS_APISERVER_MONGODB_HOST=${MONGODB_HOST}:${MONGODB_PORT}
QS_APISERVER_MONGODB_USERNAME=${MONGODB_USERNAME}
QS_APISERVER_MONGODB_PASSWORD=${MONGODB_PASSWORD}
QS_APISERVER_MONGODB_DATABASE=${MONGODB_DBNAME}

QS_APISERVER_MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
QS_APISERVER_MYSQL_USERNAME=${MYSQL_USERNAME}
QS_APISERVER_MYSQL_PASSWORD=${MYSQL_PASSWORD}
QS_APISERVER_MYSQL_DATABASE=${MYSQL_DATABASE}

# Redis single instance.
QS_APISERVER_REDIS_HOST=${REDIS_HOST}
QS_APISERVER_REDIS_PORT=${REDIS_PORT}
QS_APISERVER_REDIS_USERNAME=${REDIS_USERNAME:-}
QS_APISERVER_REDIS_PASSWORD=${REDIS_PASSWORD:-}
QS_APISERVER_REDIS_DB=${REDIS_DB}
QS_APISERVER_REDIS_USE_SSL=${REDIS_USE_SSL}
QS_APISERVER_REDIS_SSL_INSECURE_SKIP_VERIFY=${REDIS_SSL_INSECURE_SKIP_VERIFY}

QS_APISERVER_JWT_SECRET=${JWT_SECRET}

QS_APISERVER_NSQ_NSQD_HOST=${NSQ_NSQD_HOST}
QS_APISERVER_NSQ_NSQD_PORT=${NSQ_NSQD_PORT}

QS_APISERVER_OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
QS_APISERVER_OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
QS_APISERVER_OSS_SESSION_TOKEN=${OSS_SESSION_TOKEN:-}
EOF
    ;;
  collection)
    REDIS_PORT="${REDIS_PORT:-6379}"
    default_redis_ssl
    require_env REDIS_HOST REDIS_PORT JWT_SECRET

    cat > "$ENV_FILE" <<EOF
# Auto-generated production environment configuration for Collection Server
# Redis single instance.
COLLECTION_SERVER_REDIS_HOST=${REDIS_HOST}
COLLECTION_SERVER_REDIS_PORT=${REDIS_PORT}
COLLECTION_SERVER_REDIS_USERNAME=${REDIS_USERNAME:-}
COLLECTION_SERVER_REDIS_PASSWORD=${REDIS_PASSWORD:-}
COLLECTION_SERVER_REDIS_DB=${REDIS_DB}
COLLECTION_SERVER_REDIS_USE_SSL=${REDIS_USE_SSL}
COLLECTION_SERVER_REDIS_SSL_INSECURE_SKIP_VERIFY=${REDIS_SSL_INSECURE_SKIP_VERIFY}

COLLECTION_SERVER_JWT_SECRET=${JWT_SECRET}
EOF
    ;;
  worker)
    MONGODB_PORT="${MONGODB_PORT:-27017}"
    MYSQL_PORT="${MYSQL_PORT:-3306}"
    NSQ_NSQD_PORT="${NSQ_NSQD_PORT:-4150}"
    NSQ_LOOKUPD_PORT="${NSQ_LOOKUPD_PORT:-4161}"
    GRPC_APISERVER_ADDR="${GRPC_APISERVER_ADDR:-qs-apiserver:9090}"
    REDIS_PORT="${REDIS_PORT:-6379}"
    default_redis_ssl
    require_env \
      MONGODB_HOST MONGODB_PORT MONGODB_USERNAME MONGODB_PASSWORD MONGODB_DBNAME \
      MYSQL_HOST MYSQL_PORT MYSQL_USERNAME MYSQL_PASSWORD MYSQL_DATABASE \
      NSQ_NSQD_HOST NSQ_NSQD_PORT NSQ_LOOKUPD_HOST NSQ_LOOKUPD_PORT \
      REDIS_HOST REDIS_PORT

    cat > "$ENV_FILE" <<EOF
# Auto-generated production environment configuration for QS Worker
# MongoDB split parameter configuration.
QS_WORKER_MONGODB_HOST=${MONGODB_HOST}:${MONGODB_PORT}
QS_WORKER_MONGODB_USERNAME=${MONGODB_USERNAME}
QS_WORKER_MONGODB_PASSWORD=${MONGODB_PASSWORD}
QS_WORKER_MONGODB_DATABASE=${MONGODB_DBNAME}

QS_WORKER_MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
QS_WORKER_MYSQL_USERNAME=${MYSQL_USERNAME}
QS_WORKER_MYSQL_PASSWORD=${MYSQL_PASSWORD}
QS_WORKER_MYSQL_DATABASE=${MYSQL_DATABASE}

QS_WORKER_MESSAGING_PROVIDER=nsq
QS_WORKER_MESSAGING_NSQ_ADDR=${NSQ_NSQD_HOST}:${NSQ_NSQD_PORT}
QS_WORKER_MESSAGING_NSQ_LOOKUPD_ADDR=${NSQ_LOOKUPD_HOST}:${NSQ_LOOKUPD_PORT}

QS_WORKER_GRPC_APISERVER_ADDR=${GRPC_APISERVER_ADDR}

# Redis single instance.
QS_WORKER_REDIS_HOST=${REDIS_HOST}
QS_WORKER_REDIS_PORT=${REDIS_PORT}
QS_WORKER_REDIS_USERNAME=${REDIS_USERNAME:-}
QS_WORKER_REDIS_PASSWORD=${REDIS_PASSWORD:-}
QS_WORKER_REDIS_DB=${REDIS_DB}
QS_WORKER_REDIS_USE_SSL=${REDIS_USE_SSL}
QS_WORKER_REDIS_SSL_INSECURE_SKIP_VERIFY=${REDIS_SSL_INSECURE_SKIP_VERIFY}
EOF
    ;;
esac

echo "Generated config.prod.env for ${SERVICE}:"
redact_env_file "$ENV_FILE"

tar -czf "$DEPLOY_PACKAGE" -C "$PACKAGE_DIR" .
echo "Created ${DEPLOY_PACKAGE}"
