package request

import (
	"encoding/json"

	domain "github.com/FangcunMount/qs-server/internal/apiserver/domain/modelcatalog"
)

type CreateAssessmentModelRequest struct {
	Code string `json:"code"`
	// 模型族仅接受 canonical identity。
	Kind                 string   `json:"kind" valid:"required~模型类型不能为空" example:"typology" enums:"scale,typology,behavioral_rating,cognitive"`
	Algorithm            string   `json:"algorithm"`
	Title                string   `json:"title" valid:"required~模型标题不能为空"`
	Description          string   `json:"description"`
	Category             string   `json:"category"`
	Stages               []string `json:"stages"`
	ApplicableAges       []string `json:"applicable_ages"`
	Reporters            []string `json:"reporters"`
	Tags                 []string `json:"tags"`
	QuestionnaireCode    string   `json:"questionnaire_code"`
	QuestionnaireVersion string   `json:"questionnaire_version"`
}

type UpdateAssessmentModelBasicInfoRequest struct {
	Title          string   `json:"title" valid:"required~模型标题不能为空"`
	Description    string   `json:"description"`
	Algorithm      string   `json:"algorithm"`
	Category       string   `json:"category"`
	Stages         []string `json:"stages"`
	ApplicableAges []string `json:"applicable_ages"`
	Reporters      []string `json:"reporters"`
	Tags           []string `json:"tags"`
}

type BindAssessmentModelQuestionnaireRequest struct {
	QuestionnaireCode    string `json:"questionnaire_code" valid:"required~问卷编码不能为空"`
	QuestionnaireVersion string `json:"questionnaire_version" valid:"required~问卷版本不能为空"`
}

// UpdateAssessmentModelDefinitionRequest is the canonical DefinitionV2 wire
// contract. Published payloads are generated by the application service and
// are never accepted from REST authoring callers.
type UpdateAssessmentModelDefinitionRequest = domain.Definition

type ApplyAssessmentModelCodesRequest struct {
	Target string `json:"target" valid:"required~编码目标不能为空"`
	Count  int    `json:"count"`
}

type PreviewAssessmentModelReportRequest struct {
	Answers  json.RawMessage `json:"answers,omitempty"`
	SampleID string          `json:"sample_id,omitempty"`
}
