// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/apiserver/interface/grpc/proto/answersheet/answersheet.proto

package answersheet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 答卷信息
type AnswerSheet struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionnaireCode    string                 `protobuf:"bytes,2,opt,name=questionnaire_code,json=questionnaireCode,proto3" json:"questionnaire_code,omitempty"`
	QuestionnaireVersion string                 `protobuf:"bytes,3,opt,name=questionnaire_version,json=questionnaireVersion,proto3" json:"questionnaire_version,omitempty"`
	Title                string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Score                float64                 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	WriterId             uint64                 `protobuf:"varint,6,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	WriterName           string                 `protobuf:"bytes,7,opt,name=writer_name,json=writerName,proto3" json:"writer_name,omitempty"`
	TesteeId             uint64                 `protobuf:"varint,8,opt,name=testee_id,json=testeeId,proto3" json:"testee_id,omitempty"`
	TesteeName           string                 `protobuf:"bytes,9,opt,name=testee_name,json=testeeName,proto3" json:"testee_name,omitempty"`
	Answers              []*Answer              `protobuf:"bytes,10,rep,name=answers,proto3" json:"answers,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnswerSheet) Reset() {
	*x = AnswerSheet{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerSheet) ProtoMessage() {}

func (x *AnswerSheet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerSheet.ProtoReflect.Descriptor instead.
func (*AnswerSheet) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{0}
}

func (x *AnswerSheet) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerSheet) GetQuestionnaireCode() string {
	if x != nil {
		return x.QuestionnaireCode
	}
	return ""
}

func (x *AnswerSheet) GetQuestionnaireVersion() string {
	if x != nil {
		return x.QuestionnaireVersion
	}
	return ""
}

func (x *AnswerSheet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnswerSheet) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnswerSheet) GetWriterId() uint64 {
	if x != nil {
		return x.WriterId
	}
	return 0
}

func (x *AnswerSheet) GetWriterName() string {
	if x != nil {
		return x.WriterName
	}
	return ""
}

func (x *AnswerSheet) GetTesteeId() uint64 {
	if x != nil {
		return x.TesteeId
	}
	return 0
}

func (x *AnswerSheet) GetTesteeName() string {
	if x != nil {
		return x.TesteeName
	}
	return ""
}

func (x *AnswerSheet) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *AnswerSheet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AnswerSheet) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 答案信息
type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionCode  string                 `protobuf:"bytes,1,opt,name=question_code,json=questionCode,proto3" json:"question_code,omitempty"`
	QuestionType  string                 `protobuf:"bytes,2,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	Score         uint32                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // JSON 字符串，可以表示各种类型的答案值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetQuestionCode() string {
	if x != nil {
		return x.QuestionCode
	}
	return ""
}

func (x *Answer) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *Answer) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Answer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 保存答卷请求
type SaveAnswerSheetRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	QuestionnaireCode    string                 `protobuf:"bytes,1,opt,name=questionnaire_code,json=questionnaireCode,proto3" json:"questionnaire_code,omitempty"`
	QuestionnaireVersion string                 `protobuf:"bytes,2,opt,name=questionnaire_version,json=questionnaireVersion,proto3" json:"questionnaire_version,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	WriterId             uint64                 `protobuf:"varint,4,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	TesteeId             uint64                 `protobuf:"varint,5,opt,name=testee_id,json=testeeId,proto3" json:"testee_id,omitempty"`
	Answers              []*Answer              `protobuf:"bytes,6,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SaveAnswerSheetRequest) Reset() {
	*x = SaveAnswerSheetRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnswerSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnswerSheetRequest) ProtoMessage() {}

func (x *SaveAnswerSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnswerSheetRequest.ProtoReflect.Descriptor instead.
func (*SaveAnswerSheetRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{2}
}

func (x *SaveAnswerSheetRequest) GetQuestionnaireCode() string {
	if x != nil {
		return x.QuestionnaireCode
	}
	return ""
}

func (x *SaveAnswerSheetRequest) GetQuestionnaireVersion() string {
	if x != nil {
		return x.QuestionnaireVersion
	}
	return ""
}

func (x *SaveAnswerSheetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveAnswerSheetRequest) GetWriterId() uint64 {
	if x != nil {
		return x.WriterId
	}
	return 0
}

func (x *SaveAnswerSheetRequest) GetTesteeId() uint64 {
	if x != nil {
		return x.TesteeId
	}
	return 0
}

func (x *SaveAnswerSheetRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

// 保存答卷响应
type SaveAnswerSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAnswerSheetResponse) Reset() {
	*x = SaveAnswerSheetResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnswerSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnswerSheetResponse) ProtoMessage() {}

func (x *SaveAnswerSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnswerSheetResponse.ProtoReflect.Descriptor instead.
func (*SaveAnswerSheetResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{3}
}

func (x *SaveAnswerSheetResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveAnswerSheetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取答卷请求
type GetAnswerSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerSheetRequest) Reset() {
	*x = GetAnswerSheetRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerSheetRequest) ProtoMessage() {}

func (x *GetAnswerSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerSheetRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerSheetRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{4}
}

func (x *GetAnswerSheetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取答卷响应
type GetAnswerSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerSheet   *AnswerSheet           `protobuf:"bytes,1,opt,name=answer_sheet,json=answerSheet,proto3" json:"answer_sheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerSheetResponse) Reset() {
	*x = GetAnswerSheetResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerSheetResponse) ProtoMessage() {}

func (x *GetAnswerSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerSheetResponse.ProtoReflect.Descriptor instead.
func (*GetAnswerSheetResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{5}
}

func (x *GetAnswerSheetResponse) GetAnswerSheet() *AnswerSheet {
	if x != nil {
		return x.AnswerSheet
	}
	return nil
}

// 获取答卷列表请求
type ListAnswerSheetsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	QuestionnaireCode    string                 `protobuf:"bytes,1,opt,name=questionnaire_code,json=questionnaireCode,proto3" json:"questionnaire_code,omitempty"`
	QuestionnaireVersion string                 `protobuf:"bytes,2,opt,name=questionnaire_version,json=questionnaireVersion,proto3" json:"questionnaire_version,omitempty"`
	WriterId             uint64                 `protobuf:"varint,3,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	TesteeId             uint64                 `protobuf:"varint,4,opt,name=testee_id,json=testeeId,proto3" json:"testee_id,omitempty"`
	Page                 int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListAnswerSheetsRequest) Reset() {
	*x = ListAnswerSheetsRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnswerSheetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnswerSheetsRequest) ProtoMessage() {}

func (x *ListAnswerSheetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnswerSheetsRequest.ProtoReflect.Descriptor instead.
func (*ListAnswerSheetsRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{6}
}

func (x *ListAnswerSheetsRequest) GetQuestionnaireCode() string {
	if x != nil {
		return x.QuestionnaireCode
	}
	return ""
}

func (x *ListAnswerSheetsRequest) GetQuestionnaireVersion() string {
	if x != nil {
		return x.QuestionnaireVersion
	}
	return ""
}

func (x *ListAnswerSheetsRequest) GetWriterId() uint64 {
	if x != nil {
		return x.WriterId
	}
	return 0
}

func (x *ListAnswerSheetsRequest) GetTesteeId() uint64 {
	if x != nil {
		return x.TesteeId
	}
	return 0
}

func (x *ListAnswerSheetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAnswerSheetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取答卷列表响应
type ListAnswerSheetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerSheets  []*AnswerSheet         `protobuf:"bytes,1,rep,name=answer_sheets,json=answerSheets,proto3" json:"answer_sheets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnswerSheetsResponse) Reset() {
	*x = ListAnswerSheetsResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnswerSheetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnswerSheetsResponse) ProtoMessage() {}

func (x *ListAnswerSheetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnswerSheetsResponse.ProtoReflect.Descriptor instead.
func (*ListAnswerSheetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{7}
}

func (x *ListAnswerSheetsResponse) GetAnswerSheets() []*AnswerSheet {
	if x != nil {
		return x.AnswerSheets
	}
	return nil
}

func (x *ListAnswerSheetsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 保存答卷答案和分数请求
type SaveAnswerSheetScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerSheetId uint64                 `protobuf:"varint,1,opt,name=answer_sheet_id,json=answerSheetId,proto3" json:"answer_sheet_id,omitempty"` // 答卷ID
	TotalScore    float64                `protobuf:"varint,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`            // 总分
	Answers       []*Answer              `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`                                     // 答案列表（包含分数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAnswerSheetScoresRequest) Reset() {
	*x = SaveAnswerSheetScoresRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnswerSheetScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnswerSheetScoresRequest) ProtoMessage() {}

func (x *SaveAnswerSheetScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnswerSheetScoresRequest.ProtoReflect.Descriptor instead.
func (*SaveAnswerSheetScoresRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{8}
}

func (x *SaveAnswerSheetScoresRequest) GetAnswerSheetId() uint64 {
	if x != nil {
		return x.AnswerSheetId
	}
	return 0
}

func (x *SaveAnswerSheetScoresRequest) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *SaveAnswerSheetScoresRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

// 保存答卷答案和分数响应
type SaveAnswerSheetScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerSheetId uint64                 `protobuf:"varint,1,opt,name=answer_sheet_id,json=answerSheetId,proto3" json:"answer_sheet_id,omitempty"` // 答卷ID
	TotalScore    uint32                 `protobuf:"varint,2,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`            // 总分
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                     // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAnswerSheetScoresResponse) Reset() {
	*x = SaveAnswerSheetScoresResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnswerSheetScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnswerSheetScoresResponse) ProtoMessage() {}

func (x *SaveAnswerSheetScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnswerSheetScoresResponse.ProtoReflect.Descriptor instead.
func (*SaveAnswerSheetScoresResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP(), []int{9}
}

func (x *SaveAnswerSheetScoresResponse) GetAnswerSheetId() uint64 {
	if x != nil {
		return x.AnswerSheetId
	}
	return 0
}

func (x *SaveAnswerSheetScoresResponse) GetTotalScore() uint32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *SaveAnswerSheetScoresResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto protoreflect.FileDescriptor

const file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDesc = "" +
	"\n" +
	"Einternal/apiserver/interface/grpc/proto/answersheet/answersheet.proto\x12\vanswersheet\"\x96\x03\n" +
	"\vAnswerSheet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12-\n" +
	"\x12questionnaire_code\x18\x02 \x01(\tR\x11questionnaireCode\x123\n" +
	"\x15questionnaire_version\x18\x03 \x01(\tR\x14questionnaireVersion\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05score\x18\x05 \x01(\rR\x05score\x12\x1b\n" +
	"\twriter_id\x18\x06 \x01(\x04R\bwriterId\x12\x1f\n" +
	"\vwriter_name\x18\a \x01(\tR\n" +
	"writerName\x12\x1b\n" +
	"\ttestee_id\x18\b \x01(\x04R\btesteeId\x12\x1f\n" +
	"\vtestee_name\x18\t \x01(\tR\n" +
	"testeeName\x12-\n" +
	"\aanswers\x18\n" +
	" \x03(\v2\x13.answersheet.AnswerR\aanswers\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"~\n" +
	"\x06Answer\x12#\n" +
	"\rquestion_code\x18\x01 \x01(\tR\fquestionCode\x12#\n" +
	"\rquestion_type\x18\x02 \x01(\tR\fquestionType\x12\x14\n" +
	"\x05score\x18\x03 \x01(\rR\x05score\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\xfb\x01\n" +
	"\x16SaveAnswerSheetRequest\x12-\n" +
	"\x12questionnaire_code\x18\x01 \x01(\tR\x11questionnaireCode\x123\n" +
	"\x15questionnaire_version\x18\x02 \x01(\tR\x14questionnaireVersion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\twriter_id\x18\x04 \x01(\x04R\bwriterId\x12\x1b\n" +
	"\ttestee_id\x18\x05 \x01(\x04R\btesteeId\x12-\n" +
	"\aanswers\x18\x06 \x03(\v2\x13.answersheet.AnswerR\aanswers\"C\n" +
	"\x17SaveAnswerSheetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15GetAnswerSheetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"U\n" +
	"\x16GetAnswerSheetResponse\x12;\n" +
	"\fanswer_sheet\x18\x01 \x01(\v2\x18.answersheet.AnswerSheetR\vanswerSheet\"\xe8\x01\n" +
	"\x17ListAnswerSheetsRequest\x12-\n" +
	"\x12questionnaire_code\x18\x01 \x01(\tR\x11questionnaireCode\x123\n" +
	"\x15questionnaire_version\x18\x02 \x01(\tR\x14questionnaireVersion\x12\x1b\n" +
	"\twriter_id\x18\x03 \x01(\x04R\bwriterId\x12\x1b\n" +
	"\ttestee_id\x18\x04 \x01(\x04R\btesteeId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"o\n" +
	"\x18ListAnswerSheetsResponse\x12=\n" +
	"\ranswer_sheets\x18\x01 \x03(\v2\x18.answersheet.AnswerSheetR\fanswerSheets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x96\x01\n" +
	"\x1cSaveAnswerSheetScoresRequest\x12&\n" +
	"\x0fanswer_sheet_id\x18\x01 \x01(\x04R\ranswerSheetId\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\rR\n" +
	"totalScore\x12-\n" +
	"\aanswers\x18\x03 \x03(\v2\x13.answersheet.AnswerR\aanswers\"\x82\x01\n" +
	"\x1dSaveAnswerSheetScoresResponse\x12&\n" +
	"\x0fanswer_sheet_id\x18\x01 \x01(\x04R\ranswerSheetId\x12\x1f\n" +
	"\vtotal_score\x18\x02 \x01(\rR\n" +
	"totalScore\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x9e\x03\n" +
	"\x12AnswerSheetService\x12\\\n" +
	"\x0fSaveAnswerSheet\x12#.answersheet.SaveAnswerSheetRequest\x1a$.answersheet.SaveAnswerSheetResponse\x12Y\n" +
	"\x0eGetAnswerSheet\x12\".answersheet.GetAnswerSheetRequest\x1a#.answersheet.GetAnswerSheetResponse\x12_\n" +
	"\x10ListAnswerSheets\x12$.answersheet.ListAnswerSheetsRequest\x1a%.answersheet.ListAnswerSheetsResponse\x12n\n" +
	"\x15SaveAnswerSheetScores\x12).answersheet.SaveAnswerSheetScoresRequest\x1a*.answersheet.SaveAnswerSheetScoresResponseB\\ZZgithub.com/fangcun-mount/qs-server/internal/apiserver/interface/grpc/proto/answersheetb\x06proto3"

var (
	file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescOnce sync.Once
	file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescData []byte
)

func file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescGZIP() []byte {
	file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescOnce.Do(func() {
		file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDesc), len(file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDesc)))
	})
	return file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDescData
}

var file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_goTypes = []any{
	(*AnswerSheet)(nil),                   // 0: answersheet.AnswerSheet
	(*Answer)(nil),                        // 1: answersheet.Answer
	(*SaveAnswerSheetRequest)(nil),        // 2: answersheet.SaveAnswerSheetRequest
	(*SaveAnswerSheetResponse)(nil),       // 3: answersheet.SaveAnswerSheetResponse
	(*GetAnswerSheetRequest)(nil),         // 4: answersheet.GetAnswerSheetRequest
	(*GetAnswerSheetResponse)(nil),        // 5: answersheet.GetAnswerSheetResponse
	(*ListAnswerSheetsRequest)(nil),       // 6: answersheet.ListAnswerSheetsRequest
	(*ListAnswerSheetsResponse)(nil),      // 7: answersheet.ListAnswerSheetsResponse
	(*SaveAnswerSheetScoresRequest)(nil),  // 8: answersheet.SaveAnswerSheetScoresRequest
	(*SaveAnswerSheetScoresResponse)(nil), // 9: answersheet.SaveAnswerSheetScoresResponse
}
var file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_depIdxs = []int32{
	1, // 0: answersheet.AnswerSheet.answers:type_name -> answersheet.Answer
	1, // 1: answersheet.SaveAnswerSheetRequest.answers:type_name -> answersheet.Answer
	0, // 2: answersheet.GetAnswerSheetResponse.answer_sheet:type_name -> answersheet.AnswerSheet
	0, // 3: answersheet.ListAnswerSheetsResponse.answer_sheets:type_name -> answersheet.AnswerSheet
	1, // 4: answersheet.SaveAnswerSheetScoresRequest.answers:type_name -> answersheet.Answer
	2, // 5: answersheet.AnswerSheetService.SaveAnswerSheet:input_type -> answersheet.SaveAnswerSheetRequest
	4, // 6: answersheet.AnswerSheetService.GetAnswerSheet:input_type -> answersheet.GetAnswerSheetRequest
	6, // 7: answersheet.AnswerSheetService.ListAnswerSheets:input_type -> answersheet.ListAnswerSheetsRequest
	8, // 8: answersheet.AnswerSheetService.SaveAnswerSheetScores:input_type -> answersheet.SaveAnswerSheetScoresRequest
	3, // 9: answersheet.AnswerSheetService.SaveAnswerSheet:output_type -> answersheet.SaveAnswerSheetResponse
	5, // 10: answersheet.AnswerSheetService.GetAnswerSheet:output_type -> answersheet.GetAnswerSheetResponse
	7, // 11: answersheet.AnswerSheetService.ListAnswerSheets:output_type -> answersheet.ListAnswerSheetsResponse
	9, // 12: answersheet.AnswerSheetService.SaveAnswerSheetScores:output_type -> answersheet.SaveAnswerSheetScoresResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_init() }
func file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_init() {
	if File_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDesc), len(file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_goTypes,
		DependencyIndexes: file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_depIdxs,
		MessageInfos:      file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_msgTypes,
	}.Build()
	File_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto = out.File
	file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_goTypes = nil
	file_internal_apiserver_interface_grpc_proto_answersheet_answersheet_proto_depIdxs = nil
}
