-- 为统计表补充审计字段，避免 Insert 时缺少 created_at/updated_at 等列

-- statistics_daily
ALTER TABLE `statistics_daily`
    ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN `deleted_at` DATETIME NULL,
    ADD COLUMN `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `deleted_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `version` INT UNSIGNED NOT NULL DEFAULT 1;

-- statistics_accumulated
ALTER TABLE `statistics_accumulated`
    ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN `deleted_at` DATETIME NULL,
    ADD COLUMN `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `deleted_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `version` INT UNSIGNED NOT NULL DEFAULT 1;

-- statistics_plan
ALTER TABLE `statistics_plan`
    ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN `deleted_at` DATETIME NULL,
    ADD COLUMN `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `deleted_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `version` INT UNSIGNED NOT NULL DEFAULT 1;
