CREATE TABLE IF NOT EXISTS `behavior_footprint` (
  `id` VARCHAR(128) NOT NULL,
  `org_id` BIGINT NOT NULL,
  `subject_type` VARCHAR(64) NOT NULL,
  `subject_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `actor_type` VARCHAR(64) NOT NULL,
  `actor_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `entry_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `clinician_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `source_clinician_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `testee_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `answersheet_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `assessment_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `report_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `event_name` VARCHAR(64) NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `properties_json` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_behavior_footprint_org_time` (`org_id`, `event_name`, `occurred_at`),
  KEY `idx_behavior_footprint_entry` (`entry_id`),
  KEY `idx_behavior_footprint_clinician` (`clinician_id`),
  KEY `idx_behavior_footprint_testee` (`testee_id`),
  KEY `idx_behavior_footprint_answersheet` (`answersheet_id`),
  KEY `idx_behavior_footprint_assessment` (`assessment_id`),
  KEY `idx_behavior_footprint_report` (`report_id`),
  KEY `idx_behavior_footprint_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assessment_episode` (
  `episode_id` BIGINT UNSIGNED NOT NULL,
  `org_id` BIGINT NOT NULL,
  `entry_id` BIGINT UNSIGNED NULL,
  `clinician_id` BIGINT UNSIGNED NULL,
  `testee_id` BIGINT UNSIGNED NOT NULL,
  `answersheet_id` BIGINT UNSIGNED NOT NULL,
  `assessment_id` BIGINT UNSIGNED NULL,
  `report_id` BIGINT UNSIGNED NULL,
  `attributed_intake_at` DATETIME(3) NULL DEFAULT NULL,
  `submitted_at` DATETIME(3) NOT NULL,
  `assessment_created_at` DATETIME(3) NULL DEFAULT NULL,
  `report_generated_at` DATETIME(3) NULL DEFAULT NULL,
  `failed_at` DATETIME(3) NULL DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL,
  `failure_reason` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`episode_id`),
  UNIQUE KEY `uk_assessment_episode_answersheet_id` (`answersheet_id`),
  KEY `idx_assessment_episode_org_testee` (`org_id`, `testee_id`),
  KEY `idx_assessment_episode_entry` (`entry_id`),
  KEY `idx_assessment_episode_clinician` (`clinician_id`),
  KEY `idx_assessment_episode_assessment` (`assessment_id`),
  KEY `idx_assessment_episode_report` (`report_id`),
  KEY `idx_assessment_episode_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytics_projection_org_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `stat_date` DATE NOT NULL,
  `entry_opened_count` BIGINT NOT NULL DEFAULT 0,
  `intake_confirmed_count` BIGINT NOT NULL DEFAULT 0,
  `testee_profile_created_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_established_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_transferred_count` BIGINT NOT NULL DEFAULT 0,
  `answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `episode_completed_count` BIGINT NOT NULL DEFAULT 0,
  `episode_failed_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_analytics_projection_org_daily` (`org_id`, `stat_date`),
  KEY `idx_analytics_projection_org_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytics_projection_clinician_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `clinician_id` BIGINT UNSIGNED NOT NULL,
  `stat_date` DATE NOT NULL,
  `entry_opened_count` BIGINT NOT NULL DEFAULT 0,
  `intake_confirmed_count` BIGINT NOT NULL DEFAULT 0,
  `testee_profile_created_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_established_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_transferred_count` BIGINT NOT NULL DEFAULT 0,
  `answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `episode_completed_count` BIGINT NOT NULL DEFAULT 0,
  `episode_failed_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_analytics_projection_clinician_daily` (`org_id`, `clinician_id`, `stat_date`),
  KEY `idx_analytics_projection_clinician_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytics_projection_entry_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `entry_id` BIGINT UNSIGNED NOT NULL,
  `clinician_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `stat_date` DATE NOT NULL,
  `entry_opened_count` BIGINT NOT NULL DEFAULT 0,
  `intake_confirmed_count` BIGINT NOT NULL DEFAULT 0,
  `testee_profile_created_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_established_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_transferred_count` BIGINT NOT NULL DEFAULT 0,
  `answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `episode_completed_count` BIGINT NOT NULL DEFAULT 0,
  `episode_failed_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_analytics_projection_entry_daily` (`org_id`, `entry_id`, `stat_date`),
  KEY `idx_analytics_projection_entry_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytics_projector_checkpoint` (
  `event_id` VARCHAR(128) NOT NULL,
  `event_type` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  KEY `idx_analytics_projector_checkpoint_status` (`status`),
  KEY `idx_analytics_projector_checkpoint_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `analytics_pending_event` (
  `event_id` VARCHAR(128) NOT NULL,
  `event_type` VARCHAR(128) NOT NULL,
  `payload_json` LONGTEXT NOT NULL,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `attempt_count` BIGINT NOT NULL DEFAULT 0,
  `last_error` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  KEY `idx_analytics_pending_event_due` (`next_attempt_at`),
  KEY `idx_analytics_pending_event_type` (`event_type`),
  KEY `idx_analytics_pending_event_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
