CREATE TABLE IF NOT EXISTS `statistics_journey_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `subject_type` VARCHAR(32) NOT NULL,
  `subject_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `clinician_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `entry_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `stat_date` DATE NOT NULL,
  `entry_opened_count` BIGINT NOT NULL DEFAULT 0,
  `intake_confirmed_count` BIGINT NOT NULL DEFAULT 0,
  `testee_profile_created_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_established_count` BIGINT NOT NULL DEFAULT 0,
  `care_relationship_transferred_count` BIGINT NOT NULL DEFAULT 0,
  `answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `episode_completed_count` BIGINT NOT NULL DEFAULT 0,
  `episode_failed_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_failed_count` BIGINT NOT NULL DEFAULT 0,
  `access_entry_opened_count` BIGINT NOT NULL DEFAULT 0,
  `access_intake_confirmed_count` BIGINT NOT NULL DEFAULT 0,
  `access_testee_created_count` BIGINT NOT NULL DEFAULT 0,
  `access_care_relationship_established_count` BIGINT NOT NULL DEFAULT 0,
  `service_answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `service_assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `service_report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `service_assessment_failed_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_statistics_journey_daily` (`org_id`, `subject_type`, `subject_id`, `stat_date`),
  KEY `idx_statistics_journey_org_date` (`org_id`, `stat_date`),
  KEY `idx_statistics_journey_clinician_date` (`org_id`, `clinician_id`, `stat_date`),
  KEY `idx_statistics_journey_entry_date` (`org_id`, `entry_id`, `stat_date`),
  KEY `idx_statistics_journey_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `statistics_content_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `content_type` VARCHAR(50) NOT NULL,
  `content_code` VARCHAR(100) NOT NULL,
  `origin_type` VARCHAR(50) NOT NULL DEFAULT '',
  `stat_date` DATE NOT NULL,
  `submission_count` BIGINT NOT NULL DEFAULT 0,
  `completion_count` BIGINT NOT NULL DEFAULT 0,
  `answersheet_submitted_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_created_count` BIGINT NOT NULL DEFAULT 0,
  `report_generated_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_failed_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_statistics_content_daily` (`org_id`, `content_type`, `content_code`, `origin_type`, `stat_date`),
  KEY `idx_statistics_content_org_date` (`org_id`, `stat_date`),
  KEY `idx_statistics_content_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `statistics_plan_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `plan_id` BIGINT UNSIGNED NOT NULL,
  `stat_date` DATE NOT NULL,
  `task_created_count` BIGINT NOT NULL DEFAULT 0,
  `task_opened_count` BIGINT NOT NULL DEFAULT 0,
  `task_completed_count` BIGINT NOT NULL DEFAULT 0,
  `task_expired_count` BIGINT NOT NULL DEFAULT 0,
  `enrolled_testees` BIGINT NOT NULL DEFAULT 0,
  `active_testees` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_statistics_plan_daily` (`org_id`, `plan_id`, `stat_date`),
  KEY `idx_statistics_plan_org_date` (`org_id`, `stat_date`),
  KEY `idx_statistics_plan_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `statistics_org_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL,
  `testee_count` BIGINT NOT NULL DEFAULT 0,
  `clinician_count` BIGINT NOT NULL DEFAULT 0,
  `active_entry_count` BIGINT NOT NULL DEFAULT 0,
  `assessment_count` BIGINT NOT NULL DEFAULT 0,
  `report_count` BIGINT NOT NULL DEFAULT 0,
  `dimension_clinician_count` BIGINT NOT NULL DEFAULT 0,
  `dimension_entry_count` BIGINT NOT NULL DEFAULT 0,
  `dimension_content_count` BIGINT NOT NULL DEFAULT 0,
  `snapshot_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_statistics_org_snapshot_org` (`org_id`),
  KEY `idx_statistics_org_snapshot_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
