-- 初始化从业者、从业者-受试者关系、测评入口表结构
-- 创建时间: 2026-03-31
-- 版本: v8

CREATE TABLE IF NOT EXISTS `clinician` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` bigint NOT NULL COMMENT '机构ID',
  `operator_id` bigint unsigned DEFAULT NULL COMMENT '关联后台操作者ID',
  `name` varchar(100) NOT NULL COMMENT '姓名',
  `department` varchar(100) DEFAULT NULL COMMENT '科室',
  `title` varchar(100) DEFAULT NULL COMMENT '职称',
  `clinician_type` varchar(50) NOT NULL COMMENT '从业者类型',
  `employee_code` varchar(50) DEFAULT NULL COMMENT '工号',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否激活',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间（软删除）',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
  `deleted_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '删除人ID',
  `version` int unsigned NOT NULL DEFAULT '1' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clinician_org_operator` (`org_id`, `operator_id`),
  UNIQUE KEY `uk_clinician_org_employee_code` (`org_id`, `employee_code`),
  KEY `idx_org_id` (`org_id`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_name` (`name`),
  KEY `idx_clinician_type` (`clinician_type`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务从业者表';

CREATE TABLE IF NOT EXISTS `clinician_relation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` bigint NOT NULL COMMENT '机构ID',
  `clinician_id` bigint unsigned NOT NULL COMMENT '从业者ID',
  `testee_id` bigint unsigned NOT NULL COMMENT '受试者ID',
  `relation_type` varchar(50) NOT NULL COMMENT '关系类型',
  `source_type` varchar(50) NOT NULL COMMENT '来源类型',
  `source_id` bigint unsigned DEFAULT NULL COMMENT '来源对象ID',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否有效',
  `bound_at` datetime NOT NULL COMMENT '绑定时间',
  `unbound_at` datetime DEFAULT NULL COMMENT '解绑时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间（软删除）',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
  `deleted_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '删除人ID',
  `version` int unsigned NOT NULL DEFAULT '1' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clinician_testee_relation_active` (`org_id`, `clinician_id`, `testee_id`, `relation_type`, `is_active`),
  KEY `idx_org_id` (`org_id`),
  KEY `idx_clinician_id` (`clinician_id`),
  KEY `idx_testee_id` (`testee_id`),
  KEY `idx_relation_type` (`relation_type`),
  KEY `idx_source_type` (`source_type`),
  KEY `idx_source_id` (`source_id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='从业者与受试者关系表';

CREATE TABLE IF NOT EXISTS `assessment_entry` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` bigint NOT NULL COMMENT '机构ID',
  `clinician_id` bigint unsigned NOT NULL COMMENT '从业者ID',
  `token` varchar(32) NOT NULL COMMENT '入口令牌',
  `target_type` varchar(50) NOT NULL COMMENT '目标类型',
  `target_code` varchar(100) NOT NULL COMMENT '目标编码',
  `target_version` varchar(50) DEFAULT NULL COMMENT '目标版本',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否激活',
  `expires_at` datetime DEFAULT NULL COMMENT '过期时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间（软删除）',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
  `deleted_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '删除人ID',
  `version` int unsigned NOT NULL DEFAULT '1' COMMENT '版本号（乐观锁）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_token` (`token`),
  KEY `idx_org_id` (`org_id`),
  KEY `idx_clinician_id` (`clinician_id`),
  KEY `idx_target_type` (`target_type`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_expires_at` (`expires_at`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='测评入口表';
