CREATE TABLE `retry_event_hold` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `message_id` varchar(128) NOT NULL,
  `org_id` bigint DEFAULT NULL,
  `provider` varchar(32) NOT NULL,
  `topic_name` varchar(128) NOT NULL,
  `channel_name` varchar(128) NOT NULL,
  `payload_json` longtext NOT NULL,
  `original_delivery_attempt` int unsigned NOT NULL,
  `blocked_reason` varchar(255) NOT NULL,
  `blocked_at` datetime(3) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'blocked',
  `retry_disposition` varchar(32) DEFAULT 'automatic',
  `replay_attempt_count` int unsigned NOT NULL DEFAULT 0,
  `next_attempt_at` datetime(3) DEFAULT NULL,
  `claim_token` varchar(64) DEFAULT NULL,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `last_error` text NULL,
  `manual_replay_request_id` varchar(64) DEFAULT NULL,
  `replayed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_retry_event_hold_delivery` (`provider`, `topic_name`, `channel_name`, `message_id`),
  KEY `idx_retry_event_hold_due` (`status`, `retry_disposition`, `next_attempt_at`, `claim_expires_at`),
  KEY `idx_retry_event_hold_org_governance` (`org_id`, `retry_disposition`, `updated_at`),
  KEY `idx_retry_event_hold_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
