-- Add bounded, business-local historical source conclusions. No message body,
-- message creation, ACK or standard-reference semantics are introduced.
-- JSON_SCHEMA_VALID draft-4 CHECK support: MySQL 8.0.17+ / 8.4.
-- Global old-source uniqueness and authenticity remain verifier obligations.

ALTER TABLE `assessment`
  ADD COLUMN `historical_lifecycle_evidence` JSON NULL,
  ADD CONSTRAINT `chk_assessment_historical_lifecycle` CHECK (
    `historical_lifecycle_evidence` IS NULL OR (
      JSON_SCHEMA_VALID('{"type":"object","additionalProperties":false,"required":["version","entries"],"properties":{"version":{"enum":[1]},"entries":{"type":"array","minItems":1,"maxItems":128,"items":{"type":"object","additionalProperties":false,"required":["event_id","event_type","source","proof"],"properties":{"event_id":{"type":"string","minLength":1,"maxLength":128},"event_type":{"enum":["evaluation.requested","evaluation.retry.requested","evaluation.failed"]},"source":{"type":"object","additionalProperties":false,"required":["database","object","primary_key_kind","primary_key_sha256","digest"],"properties":{"database":{"enum":["mysql"]},"object":{"enum":["domain_event_outbox"]},"primary_key_kind":{"enum":["mysql_uint64"]},"primary_key_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"digest":{"type":"object","additionalProperties":false,"required":["kind","sha256"],"properties":{"kind":{"type":"string","minLength":1,"maxLength":64},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"}}}}},"proof":{"type":"object","additionalProperties":false,"required":["version","class","event_id","digest","business_binding_sha256","origin","verification"],"properties":{"version":{"enum":[1]},"class":{"enum":["retired_verified","unverifiable"]},"event_id":{"type":"string","minLength":1,"maxLength":128},"digest":{"type":"object","additionalProperties":false,"required":["kind","sha256"],"properties":{"kind":{"type":"string","minLength":1,"maxLength":64},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"}}},"business_binding_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"origin":{"enum":["retirement"]},"verification":{"type":"object","additionalProperties":false,"required":["method","version","operation_id","verified_at","business_terminal","ownership_verified","responsibility_closed"],"properties":{"method":{"type":"string","minLength":1,"maxLength":128},"version":{"type":"string","minLength":1,"maxLength":64},"operation_id":{"type":"string","pattern":"^[0-9]{1,20}-[0-9]{1,4}$"},"reason":{"type":"string","minLength":0,"maxLength":4096},"verified_at":{"type":"string","minLength":1,"maxLength":64},"business_terminal":{"enum":[true]},"ownership_verified":{"enum":[true]},"responsibility_closed":{"enum":[true]}}}}},"run":{"type":"object","additionalProperties":false,"required":["run_id","attempt"],"properties":{"run_id":{"type":"string","minLength":1,"maxLength":128},"attempt":{"type":"integer","minimum":1,"maximum":4294967295}}}}}}}}', `historical_lifecycle_evidence`)
      AND OCTET_LENGTH(CAST(`historical_lifecycle_evidence` AS CHAR CHARACTER SET utf8mb4)) <= 524288
    )
  );

ALTER TABLE `evaluation_outcome`
  ADD COLUMN `historical_committed_evidence` JSON NULL,
  ADD CONSTRAINT `chk_outcome_historical_committed` CHECK (
    `historical_committed_evidence` IS NULL OR (
      JSON_SCHEMA_VALID('{"type":"object","additionalProperties":false,"required":["version","entries"],"properties":{"version":{"enum":[1]},"entries":{"type":"array","minItems":1,"maxItems":128,"items":{"type":"object","additionalProperties":false,"required":["event_id","event_type","source","proof"],"properties":{"event_id":{"type":"string","minLength":1,"maxLength":128},"event_type":{"enum":["evaluation.outcome.committed"]},"source":{"type":"object","additionalProperties":false,"required":["database","object","primary_key_kind","primary_key_sha256","digest"],"properties":{"database":{"enum":["mysql"]},"object":{"enum":["domain_event_outbox"]},"primary_key_kind":{"enum":["mysql_uint64"]},"primary_key_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"digest":{"type":"object","additionalProperties":false,"required":["kind","sha256"],"properties":{"kind":{"type":"string","minLength":1,"maxLength":64},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"}}}}},"proof":{"type":"object","additionalProperties":false,"required":["version","class","event_id","digest","business_binding_sha256","origin","verification"],"properties":{"version":{"enum":[1]},"class":{"enum":["retired_verified","unverifiable"]},"event_id":{"type":"string","minLength":1,"maxLength":128},"digest":{"type":"object","additionalProperties":false,"required":["kind","sha256"],"properties":{"kind":{"type":"string","minLength":1,"maxLength":64},"sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"}}},"business_binding_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$"},"origin":{"enum":["retirement"]},"verification":{"type":"object","additionalProperties":false,"required":["method","version","operation_id","verified_at","business_terminal","ownership_verified","responsibility_closed"],"properties":{"method":{"type":"string","minLength":1,"maxLength":128},"version":{"type":"string","minLength":1,"maxLength":64},"operation_id":{"type":"string","pattern":"^[0-9]{1,20}-[0-9]{1,4}$"},"reason":{"type":"string","minLength":0,"maxLength":4096},"verified_at":{"type":"string","minLength":1,"maxLength":64},"business_terminal":{"enum":[true]},"ownership_verified":{"enum":[true]},"responsibility_closed":{"enum":[true]}}}}},"run":{"type":"object","additionalProperties":false,"required":["run_id","attempt"],"properties":{"run_id":{"type":"string","minLength":1,"maxLength":128},"attempt":{"type":"integer","minimum":1,"maximum":4294967295}}}}}}}}', `historical_committed_evidence`)
      AND OCTET_LENGTH(CAST(`historical_committed_evidence` AS CHAR CHARACTER SET utf8mb4)) <= 524288
    )
  );
