# Collection Server 配置文件

# 服务器配置
insecure:
  bind-address: "127.0.0.1"
  bind-port: 9081

# 安全服务配置
secure:
  bind-address: "127.0.0.1"
  bind-port: 9445
  tls:
    cert-file: "./configs/cert/collection-server.crt"
    private-key-file: "./configs/cert/collection-server.key"

# GRPC 客户端配置
grpc_client:
  endpoint: "127.0.0.1:9090"
  timeout: 30
  insecure: true

# 日志配置
log:
  name: "collection-server"
  level: "debug" # 日志级别：debug, info, warn, error, fatal, panic
  format: "console" # 日志格式：console, json
  enable-color: true # 是否开启颜色
  disable-caller: false # 是否禁用调用者
  disable-stacktrace: false # 是否禁用堆栈跟踪
  development: false # 是否为开发环境
  output-paths: ["/data/logs/qs/collection-server.log", "stdout"] # 输出路径
  error-output-paths: ["/data/logs/qs/collection-server-error.log", "stderr"] # 错误输出路径
  max-size: 100 # 单个日志文件最大大小（MB）
  max-age: 30 # 保留旧日志文件的最大天数
  max-backups: 10 # 保留旧日志文件的最大个数
  compress: true # 是否压缩旧日志文件

# Redis 配置
redis:
  host: 127.0.0.1              # Redis 服务器主机
  port: 6379                   # Redis 服务器端口
  password: questionnaire_redis_2024  # Redis 密码
  database: 0                  # Redis 数据库编号
  max-idle: 50                 # 最大空闲连接数
  max-active: 100              # 最大活跃连接数
  timeout: 5                   # 连接超时时间（秒）