# Collection Server 配置文件

# 服务器配置
server:
  mode: debug                    # 运行模式: debug, test, release
  healthz: true                  # 启用健康检查
  middlewares:                   # 中间件列表
    - logger
    - cors
    - requestid

# 日志配置
log:
  name: collection-server        # 日志名称
  development: true              # 开发模式
  level: debug                   # 日志级别
  format: console               # 日志格式: json, console
  enable-color: true            # 启用颜色
  disable-caller: false         # 禁用调用者信息
  disable-stacktrace: false     # 禁用堆栈跟踪
  output-paths:                 # 输出路径
    - stdout
    - logs/collection-server.log
  error-output-paths:           # 错误输出路径
    - stderr
    - logs/collection-server-error.log

# 不安全服务配置
insecure:
  bind-address: 0.0.0.0         # 绑定地址
  bind-port: 8081               # 绑定端口

# 安全服务配置
secure:
  bind-address: 0.0.0.0         # 绑定地址
  bind-port: 8444               # 绑定端口
  tls:
    cert-dir: configs/cert      # 证书目录
    pair-name: collection-server # 证书对名称

# GRPC 客户端配置
grpc_client:
  endpoint: localhost:8090      # apiserver GRPC 服务地址
  timeout: 30                   # 超时时间（秒）
  insecure: true               # 是否使用不安全连接 