# Evaluation Server 配置文件

# 服务器配置
server:
  mode: debug                # 运行模式: debug, release, test
  healthz: true             # 启用健康检查
  middlewares: requestid,logger,recovery,cors  # 中间件

# 不安全服务配置（健康检查）
insecure:
  bind-address: 0.0.0.0     # 绑定地址
  bind-port: 8082           # 绑定端口

# 安全服务配置（如果需要）
secure:
  bind-address: 0.0.0.0     # 绑定地址
  bind-port: 8443           # 绑定端口
  tls:
    cert-key:
      cert-file: ""         # 证书文件路径
      private-key-file: ""  # 私钥文件路径

# gRPC 客户端配置（连接到 apiserver）
grpc-client:
  endpoint: "localhost:8090"  # apiserver 的 gRPC 端点
  timeout: 30                 # 超时时间（秒）
  insecure: true             # 是否使用不安全连接

# 消息队列配置
message-queue:
  type: "redis"                    # 队列类型：redis, rabbitmq, kafka
  endpoint: "localhost:6379"       # 队列连接地址
  topic: "answersheet_saved"       # 主题/队列名称
  group: "evaluation_group"        # 消费者组
  username: ""                     # 用户名
  password: ""                     # 密码

# 日志配置
log:
  name: evaluation-server          # 日志名称
  development: true                # 开发模式
  level: debug                     # 日志级别: debug, info, warn, error, dpanic, panic, fatal
  format: console                  # 日志格式: json, console
  enable-color: true               # 启用颜色
  disable-caller: false            # 禁用调用者信息
  disable-stacktrace: false        # 禁用堆栈跟踪
  output-paths:
    - stdout
    - ./logs/evaluation-server.log
  error-output-paths:
    - stderr
    - ./logs/evaluation-server.error.log 