# Evaluation Server 配置文件

# 服务器配置
server:
  mode: "debug"                    # 运行模式: debug, test, release
  healthz: true                  # 启用健康检查
  middlewares:                   # 中间件列表
    - "logger"
    - "cors"
    - "requestid"

# 不安全服务配置
insecure:
  bind-address: "127.0.0.1"         # 绑定地址
  bind-port: 9082               # 绑定端口

# 安全服务配置
secure:
  bind-address: "127.0.0.1"         # 绑定地址
  bind-port: 9445               # 绑定端口
  Required: true
  tls:
    cert-key:
      cert-file: "configs/cert/evaluation-server.crt"
      private-key-file: "configs/cert/evaluation-server.key"
    cert-dir: "configs/cert"
    pair-name: "evaluation-server"
  AdvertiseAddress: ""

# GRPC 客户端配置
grpc_client:
  endpoint: "localhost:8090"      # apiserver GRPC 服务地址
  timeout: 30                   # 超时时间（秒）
  insecure: true               # 是否使用不安全连接

# 消息队列配置
message_queue:
  type: redis                   # 队列类型：redis, rabbitmq, kafka
  endpoint: localhost:6379      # Redis 服务器地址
  topic: answersheet.saved      # 订阅的主题
  group: evaluation_group       # 消费者组
  username: ""                  # 用户名
  password: questionnaire_redis_2024  # Redis 密码 

redis:
  host: "127.0.0.1"
  port: 6379
  database: 0
  max-idle: 50
  max-active: 100
  timeout: 5 

# 日志配置
log:
  name: "evaluation-server"
  level: "debug" # 日志级别：debug, info, warn, error, fatal, panic
  format: "console" # 日志格式：console, json
  enable-color: true # 是否开启颜色
  disable-caller: false # 是否禁用调用者
  disable-stacktrace: false # 是否禁用堆栈跟踪
  development: false # 是否为开发环境
  output-paths: ["/data/logs/qs/evaluation-server.log", "stdout"] # 输出路径
  error-output-paths: ["/data/logs/qs/evaluation-server-error.log", "stderr"] # 错误输出路径
  max-size: 100 # 单个日志文件最大大小（MB）
  max-age: 30 # 保留旧日志文件的最大天数
  max-backups: 10 # 保留旧日志文件的最大个数
  compress: true # 是否压缩旧日志文件
