# qs-apiserver 全配置

# RESTful 服务配置
server:
    mode: debug # server mode: release, debug, test，默认 release
    healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
    middlewares: recovery,logger,secure,nocache,cors,dump # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
    max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# 日志配置
log:
  level: "info" # 日志级别：debug, info, warn, error, fatal, panic
  format: "console" # 日志格式：console, json
  enable-color: true # 是否开启颜色
  disable-caller: false # 是否禁用调用者
  disable-stacktrace: false # 是否禁用堆栈跟踪
  development: false # 是否为开发环境
  output-paths: ["/data/logs/qs/qs-apiserver.log", "stdout"] # 输出路径
  error-output-paths: ["/data/logs/qs/qs-apiserver-error.log", "stderr"] # 错误输出路径
  max-size: 100 # 单个日志文件最大大小（MB）
  max-age: 30 # 保留旧日志文件的最大天数
  max-backups: 10 # 保留旧日志文件的最大个数
  compress: true # 是否压缩旧日志文件