// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/apiserver/interface/grpc/proto/actor/actor.proto

package actor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateTesteeRequest 创建受试者请求
type CreateTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         uint64                 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                  // 机构ID
	IamUserId     uint64                 `protobuf:"varint,2,opt,name=iam_user_id,json=iamUserId,proto3" json:"iam_user_id,omitempty"`    // IAM用户ID（成人）
	IamChildId    uint64                 `protobuf:"varint,3,opt,name=iam_child_id,json=iamChildId,proto3" json:"iam_child_id,omitempty"` // IAM儿童ID
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                  // 姓名
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`                             // 性别：1-男，2-女，3-其他
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`                          // 出生日期
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                  // 标签列表
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`                              // 来源：online_form/plan/screening/imported
	IsKeyFocus    bool                   `protobuf:"varint,9,opt,name=is_key_focus,json=isKeyFocus,proto3" json:"is_key_focus,omitempty"` // 是否重点关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTesteeRequest) Reset() {
	*x = CreateTesteeRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTesteeRequest) ProtoMessage() {}

func (x *CreateTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTesteeRequest.ProtoReflect.Descriptor instead.
func (*CreateTesteeRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTesteeRequest) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateTesteeRequest) GetIamUserId() uint64 {
	if x != nil {
		return x.IamUserId
	}
	return 0
}

func (x *CreateTesteeRequest) GetIamChildId() uint64 {
	if x != nil {
		return x.IamChildId
	}
	return 0
}

func (x *CreateTesteeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTesteeRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateTesteeRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *CreateTesteeRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTesteeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateTesteeRequest) GetIsKeyFocus() bool {
	if x != nil {
		return x.IsKeyFocus
	}
	return false
}

// GetTesteeRequest 获取受试者请求
type GetTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 受试者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTesteeRequest) Reset() {
	*x = GetTesteeRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTesteeRequest) ProtoMessage() {}

func (x *GetTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTesteeRequest.ProtoReflect.Descriptor instead.
func (*GetTesteeRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *GetTesteeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateTesteeRequest 更新受试者请求
type UpdateTesteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 受试者ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // 姓名（可选）
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`                             // 性别（可选）
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`                          // 出生日期（可选）
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                  // 标签列表（可选）
	IsKeyFocus    bool                   `protobuf:"varint,6,opt,name=is_key_focus,json=isKeyFocus,proto3" json:"is_key_focus,omitempty"` // 是否重点关注（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTesteeRequest) Reset() {
	*x = UpdateTesteeRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTesteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTesteeRequest) ProtoMessage() {}

func (x *UpdateTesteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTesteeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTesteeRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTesteeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTesteeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTesteeRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateTesteeRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateTesteeRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTesteeRequest) GetIsKeyFocus() bool {
	if x != nil {
		return x.IsKeyFocus
	}
	return false
}

// TesteeExistsRequest 检查受试者是否存在请求
type TesteeExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         uint64                 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                  // 机构ID
	IamChildId    uint64                 `protobuf:"varint,2,opt,name=iam_child_id,json=iamChildId,proto3" json:"iam_child_id,omitempty"` // IAM儿童ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeExistsRequest) Reset() {
	*x = TesteeExistsRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeExistsRequest) ProtoMessage() {}

func (x *TesteeExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeExistsRequest.ProtoReflect.Descriptor instead.
func (*TesteeExistsRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{3}
}

func (x *TesteeExistsRequest) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *TesteeExistsRequest) GetIamChildId() uint64 {
	if x != nil {
		return x.IamChildId
	}
	return 0
}

// TesteeExistsResponse 检查受试者是否存在响应
type TesteeExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`                     // 是否存在
	TesteeId      uint64                 `protobuf:"varint,2,opt,name=testee_id,json=testeeId,proto3" json:"testee_id,omitempty"` // 受试者ID（如果存在）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeExistsResponse) Reset() {
	*x = TesteeExistsResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeExistsResponse) ProtoMessage() {}

func (x *TesteeExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeExistsResponse.ProtoReflect.Descriptor instead.
func (*TesteeExistsResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{4}
}

func (x *TesteeExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *TesteeExistsResponse) GetTesteeId() uint64 {
	if x != nil {
		return x.TesteeId
	}
	return 0
}

// ListTesteesByOrgRequest 根据机构查询受试者列表请求
type ListTesteesByOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         uint64                 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"` // 机构ID
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`            // 偏移量
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`              // 限制数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTesteesByOrgRequest) Reset() {
	*x = ListTesteesByOrgRequest{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTesteesByOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTesteesByOrgRequest) ProtoMessage() {}

func (x *ListTesteesByOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTesteesByOrgRequest.ProtoReflect.Descriptor instead.
func (*ListTesteesByOrgRequest) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{5}
}

func (x *ListTesteesByOrgRequest) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ListTesteesByOrgRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTesteesByOrgRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// TesteeResponse 受试者响应
type TesteeResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 受试者ID
	OrgId      uint64                 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                   // 机构ID
	IamUserId  uint64                 `protobuf:"varint,3,opt,name=iam_user_id,json=iamUserId,proto3" json:"iam_user_id,omitempty"`     // IAM用户ID
	IamChildId uint64                 `protobuf:"varint,4,opt,name=iam_child_id,json=iamChildId,proto3" json:"iam_child_id,omitempty"`  // IAM儿童ID
	Name       string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                                   // 姓名
	Gender     int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`                              // 性别
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`                           // 出生日期
	Tags       []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                   // 标签列表
	Source     string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`                               // 来源
	IsKeyFocus bool                   `protobuf:"varint,10,opt,name=is_key_focus,json=isKeyFocus,proto3" json:"is_key_focus,omitempty"` // 是否重点关注
	// 测评统计信息
	AssessmentStats *AssessmentStats       `protobuf:"bytes,11,opt,name=assessment_stats,json=assessmentStats,proto3" json:"assessment_stats,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TesteeResponse) Reset() {
	*x = TesteeResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeResponse) ProtoMessage() {}

func (x *TesteeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeResponse.ProtoReflect.Descriptor instead.
func (*TesteeResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{6}
}

func (x *TesteeResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TesteeResponse) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *TesteeResponse) GetIamUserId() uint64 {
	if x != nil {
		return x.IamUserId
	}
	return 0
}

func (x *TesteeResponse) GetIamChildId() uint64 {
	if x != nil {
		return x.IamChildId
	}
	return 0
}

func (x *TesteeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TesteeResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *TesteeResponse) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *TesteeResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TesteeResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TesteeResponse) GetIsKeyFocus() bool {
	if x != nil {
		return x.IsKeyFocus
	}
	return false
}

func (x *TesteeResponse) GetAssessmentStats() *AssessmentStats {
	if x != nil {
		return x.AssessmentStats
	}
	return nil
}

func (x *TesteeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TesteeResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AssessmentStats 测评统计信息
type AssessmentStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCount       int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`                    // 总测评次数
	LastAssessmentAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_assessment_at,json=lastAssessmentAt,proto3" json:"last_assessment_at,omitempty"` // 最后测评时间
	LastRiskLevel    string                 `protobuf:"bytes,3,opt,name=last_risk_level,json=lastRiskLevel,proto3" json:"last_risk_level,omitempty"`          // 最后风险等级
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssessmentStats) Reset() {
	*x = AssessmentStats{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentStats) ProtoMessage() {}

func (x *AssessmentStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentStats.ProtoReflect.Descriptor instead.
func (*AssessmentStats) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{7}
}

func (x *AssessmentStats) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *AssessmentStats) GetLastAssessmentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAssessmentAt
	}
	return nil
}

func (x *AssessmentStats) GetLastRiskLevel() string {
	if x != nil {
		return x.LastRiskLevel
	}
	return ""
}

// TesteeListResponse 受试者列表响应
type TesteeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TesteeResponse      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`  // 受试者列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TesteeListResponse) Reset() {
	*x = TesteeListResponse{}
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TesteeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TesteeListResponse) ProtoMessage() {}

func (x *TesteeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TesteeListResponse.ProtoReflect.Descriptor instead.
func (*TesteeListResponse) Descriptor() ([]byte, []int) {
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP(), []int{8}
}

func (x *TesteeListResponse) GetItems() []*TesteeResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TesteeListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_internal_apiserver_interface_grpc_proto_actor_actor_proto protoreflect.FileDescriptor

const file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDesc = "" +
	"\n" +
	"9internal/apiserver/interface/grpc/proto/actor/actor.proto\x12\x05actor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\x13CreateTesteeRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x04R\x05orgId\x12\x1e\n" +
	"\viam_user_id\x18\x02 \x01(\x04R\tiamUserId\x12 \n" +
	"\fiam_child_id\x18\x03 \x01(\x04R\n" +
	"iamChildId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x126\n" +
	"\bbirthday\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12 \n" +
	"\fis_key_focus\x18\t \x01(\bR\n" +
	"isKeyFocus\"\"\n" +
	"\x10GetTesteeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xbf\x01\n" +
	"\x13UpdateTesteeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x126\n" +
	"\bbirthday\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12 \n" +
	"\fis_key_focus\x18\x06 \x01(\bR\n" +
	"isKeyFocus\"N\n" +
	"\x13TesteeExistsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x04R\x05orgId\x12 \n" +
	"\fiam_child_id\x18\x02 \x01(\x04R\n" +
	"iamChildId\"K\n" +
	"\x14TesteeExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\ttestee_id\x18\x02 \x01(\x04R\btesteeId\"^\n" +
	"\x17ListTesteesByOrgRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x04R\x05orgId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xe4\x03\n" +
	"\x0eTesteeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\x04R\x05orgId\x12\x1e\n" +
	"\viam_user_id\x18\x03 \x01(\x04R\tiamUserId\x12 \n" +
	"\fiam_child_id\x18\x04 \x01(\x04R\n" +
	"iamChildId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x126\n" +
	"\bbirthday\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12 \n" +
	"\fis_key_focus\x18\n" +
	" \x01(\bR\n" +
	"isKeyFocus\x12A\n" +
	"\x10assessment_stats\x18\v \x01(\v2\x16.actor.AssessmentStatsR\x0fassessmentStats\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa4\x01\n" +
	"\x0fAssessmentStats\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12H\n" +
	"\x12last_assessment_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastAssessmentAt\x12&\n" +
	"\x0flast_risk_level\x18\x03 \x01(\tR\rlastRiskLevel\"W\n" +
	"\x12TesteeListResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.actor.TesteeResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xe9\x02\n" +
	"\fActorService\x12A\n" +
	"\fCreateTestee\x12\x1a.actor.CreateTesteeRequest\x1a\x15.actor.TesteeResponse\x12;\n" +
	"\tGetTestee\x12\x17.actor.GetTesteeRequest\x1a\x15.actor.TesteeResponse\x12A\n" +
	"\fUpdateTestee\x12\x1a.actor.UpdateTesteeRequest\x1a\x15.actor.TesteeResponse\x12G\n" +
	"\fTesteeExists\x12\x1a.actor.TesteeExistsRequest\x1a\x1b.actor.TesteeExistsResponse\x12M\n" +
	"\x10ListTesteesByOrg\x12\x1e.actor.ListTesteesByOrgRequest\x1a\x19.actor.TesteeListResponseBQZOgithub.com/FangcunMount/qs-server/internal/apiserver/interface/grpc/proto/actorb\x06proto3"

var (
	file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescOnce sync.Once
	file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescData []byte
)

func file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescGZIP() []byte {
	file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescOnce.Do(func() {
		file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDesc), len(file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDesc)))
	})
	return file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDescData
}

var file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_apiserver_interface_grpc_proto_actor_actor_proto_goTypes = []any{
	(*CreateTesteeRequest)(nil),     // 0: actor.CreateTesteeRequest
	(*GetTesteeRequest)(nil),        // 1: actor.GetTesteeRequest
	(*UpdateTesteeRequest)(nil),     // 2: actor.UpdateTesteeRequest
	(*TesteeExistsRequest)(nil),     // 3: actor.TesteeExistsRequest
	(*TesteeExistsResponse)(nil),    // 4: actor.TesteeExistsResponse
	(*ListTesteesByOrgRequest)(nil), // 5: actor.ListTesteesByOrgRequest
	(*TesteeResponse)(nil),          // 6: actor.TesteeResponse
	(*AssessmentStats)(nil),         // 7: actor.AssessmentStats
	(*TesteeListResponse)(nil),      // 8: actor.TesteeListResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_internal_apiserver_interface_grpc_proto_actor_actor_proto_depIdxs = []int32{
	9,  // 0: actor.CreateTesteeRequest.birthday:type_name -> google.protobuf.Timestamp
	9,  // 1: actor.UpdateTesteeRequest.birthday:type_name -> google.protobuf.Timestamp
	9,  // 2: actor.TesteeResponse.birthday:type_name -> google.protobuf.Timestamp
	7,  // 3: actor.TesteeResponse.assessment_stats:type_name -> actor.AssessmentStats
	9,  // 4: actor.TesteeResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: actor.TesteeResponse.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 6: actor.AssessmentStats.last_assessment_at:type_name -> google.protobuf.Timestamp
	6,  // 7: actor.TesteeListResponse.items:type_name -> actor.TesteeResponse
	0,  // 8: actor.ActorService.CreateTestee:input_type -> actor.CreateTesteeRequest
	1,  // 9: actor.ActorService.GetTestee:input_type -> actor.GetTesteeRequest
	2,  // 10: actor.ActorService.UpdateTestee:input_type -> actor.UpdateTesteeRequest
	3,  // 11: actor.ActorService.TesteeExists:input_type -> actor.TesteeExistsRequest
	5,  // 12: actor.ActorService.ListTesteesByOrg:input_type -> actor.ListTesteesByOrgRequest
	6,  // 13: actor.ActorService.CreateTestee:output_type -> actor.TesteeResponse
	6,  // 14: actor.ActorService.GetTestee:output_type -> actor.TesteeResponse
	6,  // 15: actor.ActorService.UpdateTestee:output_type -> actor.TesteeResponse
	4,  // 16: actor.ActorService.TesteeExists:output_type -> actor.TesteeExistsResponse
	8,  // 17: actor.ActorService.ListTesteesByOrg:output_type -> actor.TesteeListResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_apiserver_interface_grpc_proto_actor_actor_proto_init() }
func file_internal_apiserver_interface_grpc_proto_actor_actor_proto_init() {
	if File_internal_apiserver_interface_grpc_proto_actor_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDesc), len(file_internal_apiserver_interface_grpc_proto_actor_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_apiserver_interface_grpc_proto_actor_actor_proto_goTypes,
		DependencyIndexes: file_internal_apiserver_interface_grpc_proto_actor_actor_proto_depIdxs,
		MessageInfos:      file_internal_apiserver_interface_grpc_proto_actor_actor_proto_msgTypes,
	}.Build()
	File_internal_apiserver_interface_grpc_proto_actor_actor_proto = out.File
	file_internal_apiserver_interface_grpc_proto_actor_actor_proto_goTypes = nil
	file_internal_apiserver_interface_grpc_proto_actor_actor_proto_depIdxs = nil
}
