// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: actor/actor.proto

package actor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActorService_CreateTestee_FullMethodName      = "/actor.ActorService/CreateTestee"
	ActorService_GetTestee_FullMethodName         = "/actor.ActorService/GetTestee"
	ActorService_UpdateTestee_FullMethodName      = "/actor.ActorService/UpdateTestee"
	ActorService_TesteeExists_FullMethodName      = "/actor.ActorService/TesteeExists"
	ActorService_ListTesteesByOrg_FullMethodName  = "/actor.ActorService/ListTesteesByOrg"
	ActorService_ListTesteesByUser_FullMethodName = "/actor.ActorService/ListTesteesByUser"
)

// ActorServiceClient is the client API for ActorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActorService Actor 服务 - 管理受试者和员工
type ActorServiceClient interface {
	// CreateTestee 创建受试者
	// 用于外部场景（collection-server）和内部场景（周期性测评创建受试者）
	CreateTestee(ctx context.Context, in *CreateTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error)
	// GetTestee 获取受试者详情
	GetTestee(ctx context.Context, in *GetTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error)
	// UpdateTestee 更新受试者信息
	UpdateTestee(ctx context.Context, in *UpdateTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error)
	// TesteeExists 检查受试者是否存在
	TesteeExists(ctx context.Context, in *TesteeExistsRequest, opts ...grpc.CallOption) (*TesteeExistsResponse, error)
	// ListTesteesByOrg 根据机构查询受试者列表
	ListTesteesByOrg(ctx context.Context, in *ListTesteesByOrgRequest, opts ...grpc.CallOption) (*TesteeListResponse, error)
	// ListTesteesByUser 根据用户（监护人）查询受试者列表
	// 用于 collection-server 查询当前用户的受试者
	ListTesteesByUser(ctx context.Context, in *ListTesteesByUserRequest, opts ...grpc.CallOption) (*TesteeListResponse, error)
}

type actorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActorServiceClient(cc grpc.ClientConnInterface) ActorServiceClient {
	return &actorServiceClient{cc}
}

func (c *actorServiceClient) CreateTestee(ctx context.Context, in *CreateTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeResponse)
	err := c.cc.Invoke(ctx, ActorService_CreateTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) GetTestee(ctx context.Context, in *GetTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeResponse)
	err := c.cc.Invoke(ctx, ActorService_GetTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) UpdateTestee(ctx context.Context, in *UpdateTesteeRequest, opts ...grpc.CallOption) (*TesteeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeResponse)
	err := c.cc.Invoke(ctx, ActorService_UpdateTestee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) TesteeExists(ctx context.Context, in *TesteeExistsRequest, opts ...grpc.CallOption) (*TesteeExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeExistsResponse)
	err := c.cc.Invoke(ctx, ActorService_TesteeExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) ListTesteesByOrg(ctx context.Context, in *ListTesteesByOrgRequest, opts ...grpc.CallOption) (*TesteeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeListResponse)
	err := c.cc.Invoke(ctx, ActorService_ListTesteesByOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorServiceClient) ListTesteesByUser(ctx context.Context, in *ListTesteesByUserRequest, opts ...grpc.CallOption) (*TesteeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TesteeListResponse)
	err := c.cc.Invoke(ctx, ActorService_ListTesteesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActorServiceServer is the server API for ActorService service.
// All implementations must embed UnimplementedActorServiceServer
// for forward compatibility.
//
// ActorService Actor 服务 - 管理受试者和员工
type ActorServiceServer interface {
	// CreateTestee 创建受试者
	// 用于外部场景（collection-server）和内部场景（周期性测评创建受试者）
	CreateTestee(context.Context, *CreateTesteeRequest) (*TesteeResponse, error)
	// GetTestee 获取受试者详情
	GetTestee(context.Context, *GetTesteeRequest) (*TesteeResponse, error)
	// UpdateTestee 更新受试者信息
	UpdateTestee(context.Context, *UpdateTesteeRequest) (*TesteeResponse, error)
	// TesteeExists 检查受试者是否存在
	TesteeExists(context.Context, *TesteeExistsRequest) (*TesteeExistsResponse, error)
	// ListTesteesByOrg 根据机构查询受试者列表
	ListTesteesByOrg(context.Context, *ListTesteesByOrgRequest) (*TesteeListResponse, error)
	// ListTesteesByUser 根据用户（监护人）查询受试者列表
	// 用于 collection-server 查询当前用户的受试者
	ListTesteesByUser(context.Context, *ListTesteesByUserRequest) (*TesteeListResponse, error)
	mustEmbedUnimplementedActorServiceServer()
}

// UnimplementedActorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActorServiceServer struct{}

func (UnimplementedActorServiceServer) CreateTestee(context.Context, *CreateTesteeRequest) (*TesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTestee not implemented")
}
func (UnimplementedActorServiceServer) GetTestee(context.Context, *GetTesteeRequest) (*TesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestee not implemented")
}
func (UnimplementedActorServiceServer) UpdateTestee(context.Context, *UpdateTesteeRequest) (*TesteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTestee not implemented")
}
func (UnimplementedActorServiceServer) TesteeExists(context.Context, *TesteeExistsRequest) (*TesteeExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TesteeExists not implemented")
}
func (UnimplementedActorServiceServer) ListTesteesByOrg(context.Context, *ListTesteesByOrgRequest) (*TesteeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTesteesByOrg not implemented")
}
func (UnimplementedActorServiceServer) ListTesteesByUser(context.Context, *ListTesteesByUserRequest) (*TesteeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTesteesByUser not implemented")
}
func (UnimplementedActorServiceServer) mustEmbedUnimplementedActorServiceServer() {}
func (UnimplementedActorServiceServer) testEmbeddedByValue()                      {}

// UnsafeActorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorServiceServer will
// result in compilation errors.
type UnsafeActorServiceServer interface {
	mustEmbedUnimplementedActorServiceServer()
}

func RegisterActorServiceServer(s grpc.ServiceRegistrar, srv ActorServiceServer) {
	// If the following call pancis, it indicates UnimplementedActorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActorService_ServiceDesc, srv)
}

func _ActorService_CreateTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).CreateTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_CreateTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).CreateTestee(ctx, req.(*CreateTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_GetTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).GetTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_GetTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).GetTestee(ctx, req.(*GetTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_UpdateTestee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTesteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).UpdateTestee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_UpdateTestee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).UpdateTestee(ctx, req.(*UpdateTesteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_TesteeExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TesteeExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).TesteeExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_TesteeExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).TesteeExists(ctx, req.(*TesteeExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_ListTesteesByOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTesteesByOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).ListTesteesByOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_ListTesteesByOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).ListTesteesByOrg(ctx, req.(*ListTesteesByOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorService_ListTesteesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTesteesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorServiceServer).ListTesteesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorService_ListTesteesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServiceServer).ListTesteesByUser(ctx, req.(*ListTesteesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActorService_ServiceDesc is the grpc.ServiceDesc for ActorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actor.ActorService",
	HandlerType: (*ActorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTestee",
			Handler:    _ActorService_CreateTestee_Handler,
		},
		{
			MethodName: "GetTestee",
			Handler:    _ActorService_GetTestee_Handler,
		},
		{
			MethodName: "UpdateTestee",
			Handler:    _ActorService_UpdateTestee_Handler,
		},
		{
			MethodName: "TesteeExists",
			Handler:    _ActorService_TesteeExists_Handler,
		},
		{
			MethodName: "ListTesteesByOrg",
			Handler:    _ActorService_ListTesteesByOrg_Handler,
		},
		{
			MethodName: "ListTesteesByUser",
			Handler:    _ActorService_ListTesteesByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "actor/actor.proto",
}
