// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: personalitymodel/personality_model.proto

package personalitymodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalityModelSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Algorithm            string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Description          string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	QuestionnaireCode    string                 `protobuf:"bytes,6,opt,name=questionnaire_code,json=questionnaireCode,proto3" json:"questionnaire_code,omitempty"`
	QuestionnaireVersion string                 `protobuf:"bytes,7,opt,name=questionnaire_version,json=questionnaireVersion,proto3" json:"questionnaire_version,omitempty"`
	Status               string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	QuestionCount        int32                  `protobuf:"varint,9,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PersonalityModelSummary) Reset() {
	*x = PersonalityModelSummary{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityModelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityModelSummary) ProtoMessage() {}

func (x *PersonalityModelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityModelSummary.ProtoReflect.Descriptor instead.
func (*PersonalityModelSummary) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalityModelSummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PersonalityModelSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PersonalityModelSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PersonalityModelSummary) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PersonalityModelSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonalityModelSummary) GetQuestionnaireCode() string {
	if x != nil {
		return x.QuestionnaireCode
	}
	return ""
}

func (x *PersonalityModelSummary) GetQuestionnaireVersion() string {
	if x != nil {
		return x.QuestionnaireVersion
	}
	return ""
}

func (x *PersonalityModelSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PersonalityModelSummary) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

type PersonalityDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LeftPole      string                 `protobuf:"bytes,3,opt,name=left_pole,json=leftPole,proto3" json:"left_pole,omitempty"`
	RightPole     string                 `protobuf:"bytes,4,opt,name=right_pole,json=rightPole,proto3" json:"right_pole,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalityDimension) Reset() {
	*x = PersonalityDimension{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityDimension) ProtoMessage() {}

func (x *PersonalityDimension) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityDimension.ProtoReflect.Descriptor instead.
func (*PersonalityDimension) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalityDimension) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PersonalityDimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalityDimension) GetLeftPole() string {
	if x != nil {
		return x.LeftPole
	}
	return ""
}

func (x *PersonalityDimension) GetRightPole() string {
	if x != nil {
		return x.RightPole
	}
	return ""
}

type PersonalityOutcomeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OneLiner      string                 `protobuf:"bytes,3,opt,name=one_liner,json=oneLiner,proto3" json:"one_liner,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalityOutcomeSummary) Reset() {
	*x = PersonalityOutcomeSummary{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityOutcomeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityOutcomeSummary) ProtoMessage() {}

func (x *PersonalityOutcomeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityOutcomeSummary.ProtoReflect.Descriptor instead.
func (*PersonalityOutcomeSummary) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalityOutcomeSummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PersonalityOutcomeSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalityOutcomeSummary) GetOneLiner() string {
	if x != nil {
		return x.OneLiner
	}
	return ""
}

func (x *PersonalityOutcomeSummary) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type PersonalityModel struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Summary        *PersonalityModelSummary     `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	DimensionOrder []string                     `protobuf:"bytes,2,rep,name=dimension_order,json=dimensionOrder,proto3" json:"dimension_order,omitempty"`
	Dimensions     []*PersonalityDimension      `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Outcomes       []*PersonalityOutcomeSummary `protobuf:"bytes,4,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonalityModel) Reset() {
	*x = PersonalityModel{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityModel) ProtoMessage() {}

func (x *PersonalityModel) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityModel.ProtoReflect.Descriptor instead.
func (*PersonalityModel) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalityModel) GetSummary() *PersonalityModelSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *PersonalityModel) GetDimensionOrder() []string {
	if x != nil {
		return x.DimensionOrder
	}
	return nil
}

func (x *PersonalityModel) GetDimensions() []*PersonalityDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *PersonalityModel) GetOutcomes() []*PersonalityOutcomeSummary {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

type PersonalityModelCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalityModelCategory) Reset() {
	*x = PersonalityModelCategory{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalityModelCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityModelCategory) ProtoMessage() {}

func (x *PersonalityModelCategory) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityModelCategory.ProtoReflect.Descriptor instead.
func (*PersonalityModelCategory) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalityModelCategory) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PersonalityModelCategory) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetPersonalityModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalityModelRequest) Reset() {
	*x = GetPersonalityModelRequest{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalityModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalityModelRequest) ProtoMessage() {}

func (x *GetPersonalityModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalityModelRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalityModelRequest) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetPersonalityModelRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetPersonalityModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *PersonalityModel      `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalityModelResponse) Reset() {
	*x = GetPersonalityModelResponse{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalityModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalityModelResponse) ProtoMessage() {}

func (x *GetPersonalityModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalityModelResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalityModelResponse) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{6}
}

func (x *GetPersonalityModelResponse) GetModel() *PersonalityModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type ListPersonalityModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonalityModelsRequest) Reset() {
	*x = ListPersonalityModelsRequest{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonalityModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonalityModelsRequest) ProtoMessage() {}

func (x *ListPersonalityModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonalityModelsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonalityModelsRequest) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{7}
}

func (x *ListPersonalityModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPersonalityModelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPersonalityModelsRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type ListPersonalityModelsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Models        []*PersonalityModelSummary `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Total         int64                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                      `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonalityModelsResponse) Reset() {
	*x = ListPersonalityModelsResponse{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonalityModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonalityModelsResponse) ProtoMessage() {}

func (x *ListPersonalityModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonalityModelsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonalityModelsResponse) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListPersonalityModelsResponse) GetModels() []*PersonalityModelSummary {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListPersonalityModelsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPersonalityModelsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPersonalityModelsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPersonalityModelsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetPersonalityModelCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalityModelCategoriesRequest) Reset() {
	*x = GetPersonalityModelCategoriesRequest{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalityModelCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalityModelCategoriesRequest) ProtoMessage() {}

func (x *GetPersonalityModelCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalityModelCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalityModelCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{9}
}

type GetPersonalityModelCategoriesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Categories    []*PersonalityModelCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalityModelCategoriesResponse) Reset() {
	*x = GetPersonalityModelCategoriesResponse{}
	mi := &file_personalitymodel_personality_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalityModelCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalityModelCategoriesResponse) ProtoMessage() {}

func (x *GetPersonalityModelCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personalitymodel_personality_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalityModelCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalityModelCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_personalitymodel_personality_model_proto_rawDescGZIP(), []int{10}
}

func (x *GetPersonalityModelCategoriesResponse) GetCategories() []*PersonalityModelCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_personalitymodel_personality_model_proto protoreflect.FileDescriptor

const file_personalitymodel_personality_model_proto_rawDesc = "" +
	"\n" +
	"(personalitymodel/personality_model.proto\x12\x10personalitymodel\"\xc0\x02\n" +
	"\x17PersonalityModelSummary\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12-\n" +
	"\x12questionnaire_code\x18\x06 \x01(\tR\x11questionnaireCode\x123\n" +
	"\x15questionnaire_version\x18\a \x01(\tR\x14questionnaireVersion\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0equestion_count\x18\t \x01(\x05R\rquestionCount\"z\n" +
	"\x14PersonalityDimension\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tleft_pole\x18\x03 \x01(\tR\bleftPole\x12\x1d\n" +
	"\n" +
	"right_pole\x18\x04 \x01(\tR\trightPole\"}\n" +
	"\x19PersonalityOutcomeSummary\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tone_liner\x18\x03 \x01(\tR\boneLiner\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"\x91\x02\n" +
	"\x10PersonalityModel\x12C\n" +
	"\asummary\x18\x01 \x01(\v2).personalitymodel.PersonalityModelSummaryR\asummary\x12'\n" +
	"\x0fdimension_order\x18\x02 \x03(\tR\x0edimensionOrder\x12F\n" +
	"\n" +
	"dimensions\x18\x03 \x03(\v2&.personalitymodel.PersonalityDimensionR\n" +
	"dimensions\x12G\n" +
	"\boutcomes\x18\x04 \x03(\v2+.personalitymodel.PersonalityOutcomeSummaryR\boutcomes\"F\n" +
	"\x18PersonalityModelCategory\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"0\n" +
	"\x1aGetPersonalityModelRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"W\n" +
	"\x1bGetPersonalityModelResponse\x128\n" +
	"\x05model\x18\x01 \x01(\v2\".personalitymodel.PersonalityModelR\x05model\"m\n" +
	"\x1cListPersonalityModelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\"\xca\x01\n" +
	"\x1dListPersonalityModelsResponse\x12A\n" +
	"\x06models\x18\x01 \x03(\v2).personalitymodel.PersonalityModelSummaryR\x06models\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"&\n" +
	"$GetPersonalityModelCategoriesRequest\"s\n" +
	"%GetPersonalityModelCategoriesResponse\x12J\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2*.personalitymodel.PersonalityModelCategoryR\n" +
	"categories2\x9a\x03\n" +
	"\x17PersonalityModelService\x12r\n" +
	"\x13GetPersonalityModel\x12,.personalitymodel.GetPersonalityModelRequest\x1a-.personalitymodel.GetPersonalityModelResponse\x12x\n" +
	"\x15ListPersonalityModels\x12..personalitymodel.ListPersonalityModelsRequest\x1a/.personalitymodel.ListPersonalityModelsResponse\x12\x90\x01\n" +
	"\x1dGetPersonalityModelCategories\x126.personalitymodel.GetPersonalityModelCategoriesRequest\x1a7.personalitymodel.GetPersonalityModelCategoriesResponseB\\ZZgithub.com/FangcunMount/qs-server/internal/apiserver/interface/grpc/proto/personalitymodelb\x06proto3"

var (
	file_personalitymodel_personality_model_proto_rawDescOnce sync.Once
	file_personalitymodel_personality_model_proto_rawDescData []byte
)

func file_personalitymodel_personality_model_proto_rawDescGZIP() []byte {
	file_personalitymodel_personality_model_proto_rawDescOnce.Do(func() {
		file_personalitymodel_personality_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_personalitymodel_personality_model_proto_rawDesc), len(file_personalitymodel_personality_model_proto_rawDesc)))
	})
	return file_personalitymodel_personality_model_proto_rawDescData
}

var file_personalitymodel_personality_model_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_personalitymodel_personality_model_proto_goTypes = []any{
	(*PersonalityModelSummary)(nil),               // 0: personalitymodel.PersonalityModelSummary
	(*PersonalityDimension)(nil),                  // 1: personalitymodel.PersonalityDimension
	(*PersonalityOutcomeSummary)(nil),             // 2: personalitymodel.PersonalityOutcomeSummary
	(*PersonalityModel)(nil),                      // 3: personalitymodel.PersonalityModel
	(*PersonalityModelCategory)(nil),              // 4: personalitymodel.PersonalityModelCategory
	(*GetPersonalityModelRequest)(nil),            // 5: personalitymodel.GetPersonalityModelRequest
	(*GetPersonalityModelResponse)(nil),           // 6: personalitymodel.GetPersonalityModelResponse
	(*ListPersonalityModelsRequest)(nil),          // 7: personalitymodel.ListPersonalityModelsRequest
	(*ListPersonalityModelsResponse)(nil),         // 8: personalitymodel.ListPersonalityModelsResponse
	(*GetPersonalityModelCategoriesRequest)(nil),  // 9: personalitymodel.GetPersonalityModelCategoriesRequest
	(*GetPersonalityModelCategoriesResponse)(nil), // 10: personalitymodel.GetPersonalityModelCategoriesResponse
}
var file_personalitymodel_personality_model_proto_depIdxs = []int32{
	0,  // 0: personalitymodel.PersonalityModel.summary:type_name -> personalitymodel.PersonalityModelSummary
	1,  // 1: personalitymodel.PersonalityModel.dimensions:type_name -> personalitymodel.PersonalityDimension
	2,  // 2: personalitymodel.PersonalityModel.outcomes:type_name -> personalitymodel.PersonalityOutcomeSummary
	3,  // 3: personalitymodel.GetPersonalityModelResponse.model:type_name -> personalitymodel.PersonalityModel
	0,  // 4: personalitymodel.ListPersonalityModelsResponse.models:type_name -> personalitymodel.PersonalityModelSummary
	4,  // 5: personalitymodel.GetPersonalityModelCategoriesResponse.categories:type_name -> personalitymodel.PersonalityModelCategory
	5,  // 6: personalitymodel.PersonalityModelService.GetPersonalityModel:input_type -> personalitymodel.GetPersonalityModelRequest
	7,  // 7: personalitymodel.PersonalityModelService.ListPersonalityModels:input_type -> personalitymodel.ListPersonalityModelsRequest
	9,  // 8: personalitymodel.PersonalityModelService.GetPersonalityModelCategories:input_type -> personalitymodel.GetPersonalityModelCategoriesRequest
	6,  // 9: personalitymodel.PersonalityModelService.GetPersonalityModel:output_type -> personalitymodel.GetPersonalityModelResponse
	8,  // 10: personalitymodel.PersonalityModelService.ListPersonalityModels:output_type -> personalitymodel.ListPersonalityModelsResponse
	10, // 11: personalitymodel.PersonalityModelService.GetPersonalityModelCategories:output_type -> personalitymodel.GetPersonalityModelCategoriesResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_personalitymodel_personality_model_proto_init() }
func file_personalitymodel_personality_model_proto_init() {
	if File_personalitymodel_personality_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_personalitymodel_personality_model_proto_rawDesc), len(file_personalitymodel_personality_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personalitymodel_personality_model_proto_goTypes,
		DependencyIndexes: file_personalitymodel_personality_model_proto_depIdxs,
		MessageInfos:      file_personalitymodel_personality_model_proto_msgTypes,
	}.Build()
	File_personalitymodel_personality_model_proto = out.File
	file_personalitymodel_personality_model_proto_goTypes = nil
	file_personalitymodel_personality_model_proto_depIdxs = nil
}
